### ISSUE TITLE
Category colours

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#100]
Would be nice if as you scroll down across the categories if the one you are on could highlight in a colour rather than a grey say in a pink or orange?  could we maybe test this out?

- Consistent size for triangles
- Colour from categories for triangles
- Block colour bar when open

**Comment by tomalrussell** [comment]
Closed by 6d054919f84e1adede810b4a1c4e30661a5a3f32 - colour in sidebar triangles and border
