### ISSUE TITLE
Add webpage  link box for each building

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#105]
Hi we need to add a place for people to add the links to pages on the building, could you add asample of how you think it might look so i can test it? The historic buildings guys will need this so that they don't find the process of simplification off putting

- Age only

**Comment by tomalrussell** [comment]
This is under 'Age' and 'Text and Image Links' - closed by 9d1094cdd577a36cec1d732567c2997be8de4a8f
