### ISSUE TITLE
Add key also bottom right page with 'Colouring London' on it

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#115]
If we add the key also in the bottom right corner it means that it you take a snip of your map it will automatically be included.  This means a) you don't have to  include the left hand bar b)  If we had the title 'Colouring London in the Key box then everytime someone takes a snip and distributes it the project will be publicised.

**Comment by tomalrussell** [comment]
Closed by a35df52b75fad9b4a69fcf095f3e324693ceb121
