### ISSUE TITLE
Add reference box under 'Age sources' & remove ' expert judgement

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#116]
Add reference box and remove expert judgement as discussed.  Colour to triiger only when this section filled in.  Would be good to have hovers saying if book add Publisher, Title Volume, page, edition. If a map add publisher, edition, date and scale,

**Comment by tomalrussell** [comment]
Source Details box added under Age. Expert knowledge left in. 

Closed by c30ffda338ab2b5302627fe9f641089f9e95dac5 and previous

**Comment by polly64** [comment]
Hi Tom I'm on that number most  day so just ring if will be before 12 and email me if after to make time I'll be near phone.


We're getting  a  build of smallbut really important  items especially  since I've been working with the PR people - these will make it much clearer to use - would be v good if you could have a go at these before we talk. Imagine items a-d very quick and e and f longer so would really like to get these out of the way, but e and f also important. There are all quite a priority- not sure where you are with other stuff. Thanks speak later


a) Make title a couple of points larger larger -View maps is nearly same size at moment at category names

b) Make summary text under categories a couple of points smaller as want categories to stand out

c) Make 'More info' on the category page into just ' Info'  - this makes clearer and will give a margin along right hand side of column which we need as looks a bit squashed( the PR person Velvet  said she thought this meant about the project as a whole as it was like  'more about' on toolbar

d) Move 'More'about' on toolbar to the end of line so it's before 'discuss'


e) Shrink colour key and lift up page so you don't have to scroll down

f)Because a lot of people have no said this  is confusing we need to:

Reverse key on 'Location' and remove lightest colour- so our lightest colour is very clear.

And On the key put

Title saying  Location data

Subtitle saying: 'What % of our location data have we collected?
Add 20%,40%,60%.80%, 100% next to each category


For the demo on the 24 we'll need to unlock London category for the day so I can have a category where I can quickly show how it colours without having to think




Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________

**Comment by polly64** [comment]
hi tom can we make a time to speak later?


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________
