### ISSUE TITLE
Team - Free Text Boxes

### ISSUE THREAD

**Issue by mdsimpson42** [tomalrussell/colouring-london#1164]
In the Team category, there are currently free-text boxes for:

- Landowner
- Developer
- Designer
- Builder

We are removing free-text boxes from the site. If we do the same as Building Name (Location), we just provide a link to a website that has the name on it. But then we don't need Source Type/Source Link(s) for those fields?

**Comment by polly64** [comment]
@mdsimpson42 actually think we do. On the source type button can we differentiate between 'current official/government record' and 'historical record' and also add 'Computational generation - inferred from other attributes' as an option
