### ISSUE TITLE
Like me  speed issue, colour

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#118]
Hi, can you have a go at liking five buildings in a row?  I'm finding the process too long to keep my attention for more than a few even though I'm motivated.  Everything colours really fast which is great.  It's just that i feel like I have to click too many things to get to the next one.  Can we make this easier?  So ideally I would be in the View maps mode, I click on the 'Like me' button and it will show me the'Like me' map (with key bottom right on map and in left hand column as well), and it has something really clear that says Add to or this map by clicking a building.  This takes me to the edit mode just for Like me (without any other categories visible) and on the left hand side there is just one button (maybe with red border)  which says 'click to like the building' ,  I click the button to colour the building  and It would be great if it just saved as coloured so we don't have to have either the 'save, or ' done' buttons, which a bit confusing.  At the top i think we just need an ' undo' button and  a 'return to categories' which takes you back to view maps.  Then I decide i want to like all the rest of the street so I click the next one, go straight to like button, click it and the building colours, go straight back to the map click the next building, then click the like button, building colours and automatically saves, I go back and click the next building etc.....  If it was this smooth it would make me put more in.  Also need colour to look different to make me feel my contribution has been added if I am adding a like to building one someone else  has already liked.

**Comment by tomalrussell** [comment]
Closed by d3907f73623b12e4b8954027bc7b06183ae8cc40 and previous:
- like/unlike colours with no additional save button
- clicking on another building leaves you in 'Edit' mode, still in the 'Like' category
