### ISSUE TITLE
Title name changes

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#120]
I'm working on subcategories and realise need to adjust names again. Also to make clearer.
1)' Energy' goes to 'Sustainability'
2)'Team' goes to 'Designer/Builder'
3) 'Design/Build' goes to 'Construction'

(I also think we can experiment with some new subcategories under 'sustainability'  which aren't really being looked at but are obviously important- 'Estimated actual lifespan' and 'Ease of repair' links into my PhD stuff which i can update u on next time)

**Comment by polly64** [comment]
Correction to this see selow
1) Energy goes to sustainability
2) Team stays as team
3) Design/build goes to construction
4) Planning goes to 'Controls

Can you change on discussion feed titles too many thanks

**Comment by polly64** [comment]
Final correction to this for wednesday
Energy goes to sustainability
Team stays as Team
Design/build goes to Construction
Planning stays as Planning

**Comment by tomalrussell** [comment]
Up-to-date as of 3ec7be04774699eacf5d39b6e486c4d011f0e760
