### ISSUE TITLE
copy tool not working on architectural style

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#1244]
Hi @matkoniecz could you possibly if you have time see what's wrong with copy tool on 'architectural style' in Age and History as Mike's away and i need to add data next week? not  working copying and pasting (it is working fine for land use so imagine it is a quick fix)

error also occurring with automatic copying of age data with architectural style without this being above to be seen - ideal to have option visible but shouldn't do automatically

**Comment by polly64** [comment]
@mdsimpson42 online now to chat re others

**Comment by mdsimpson42** [comment]
I did say I'll look into it, I'm just trying to sort through all the outstanding issue first so we can prioritise them

**Comment by mdsimpson42** [comment]
See also #1172

**Comment by mdsimpson42** [comment]
Closed in favour of #1172
