### ISSUE TITLE
problem with building colouring

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#127]
hi tom try adding location data to a row of buildings - they don't seem to want to coloured

**Comment by tomalrussell** [comment]
Keeping this one in project TODO - #130 #122 #135 #145 are all likely related:
- random likes popping up, extra polygons seeming to colour
- colouring sometimes disappearing as I move along a row

Possibly to do with the revision id, used when requesting map tiles (partly to help bust browser cache). Possible fix to keep track of max revision seen (in session? client-side state?) and only increase.

**Comment by tomalrussell** [comment]
Closed by revision id / cache-busting updates
