### ISSUE TITLE
Suggest bulk data source feature

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#136]
I think it might be worth having a page on the github wiki (or elsewhere) that allows people to see raw data in the db, suggest sources (?) and show sources that have been considered/known about and the status of the source. Ie VOA data, known about but licence restriction prevents use in project.

**Comment by tomalrussell** [comment]
Good idea - I've just created https://github.com/tomalrussell/colouring-london/wiki/Potential-data-sources - feel free to add.

Also linked across to the forum which can hopefully be a place for general how-to chat: https://discuss.colouring.london/
