### ISSUE TITLE
db Copy for listed buildings work

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#140]
Hi @tomalrussell 
I'm going to start working on listed buildings. Can i get a copy of the db (with geom) to use locally, i can then pass back the the columns including the key column for ~~population~~ id if that works with the structure you have set up? A sql dump works for me if it works for you. I'd need geom / id/ column names that relate to listed buildings page and address column as a lot of the entry include this so we can populate some of those (street etc).

**Comment by polly64** [comment]
Planning (incl listed buildings) needs to be next category for upload (Relevant to community groups, local authorities and Historic England)-  
The following are the subcategories we'll want to visualise in this section
a) listed buildings (by grade)
b) buildings in conservation areas
For  a ) I think it would be probably good for us to colour code listed buildings (3 colours), scheduled monuments, and locally listed buildings on same map.

**Comment by tomalrussell** [comment]
@dominijk yes, I can pass you the data you need to get set up - I'll drop you an email.

Ideally, you can get set up with a local development environment to test running updates against - this would be a good chance to work out a usable process for bulk uploads.

I need to set up the database fields for planning first, though - it's on the TODO list (literally: https://github.com/tomalrussell/colouring-london/projects/1).

**Comment by dominijk** [comment]
@tomalrussell Thank you, I'd like to get started on this next week if I can get a copy by then. Currently throwing things into my own PG db

**Comment by polly64** [comment]
Hi at the moment we can only use the file with borough's that have permitted release.  Dom do you have this file? email me if you don't

**Comment by dominijk** [comment]
@polly64 I think so , this is the one you circulated yesterday pm `20181108_Conservation_Areas_INSPIRE_Dataset_GLA`

**Comment by tomalrussell** [comment]
Closing this issue - created #171 to track catching **all** buildings falling within conservation areas.
