### ISSUE TITLE
Reduce number of classes for storeys

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#144]
Think too many classes- probably good to stick to 5. Can we change the core storeys to
1-5
6-10
10-19
10-39
40 upwards
If we can asap would  be great

After chrustmas perhaps we can have a total storeys box that is automatically generated when others are filled?  I think we talked about this but can't remember outcome. I think we probably in the long term we want to be able to visualise 
a) total storeys 
b) total storeys above ground i.e. attics plus core
c) basements
d) attics

**Comment by tomalrussell** [comment]
This requires a couple of changes:
- [ ] legend component in frontend: https://github.com/tomalrussell/colouring-london/blob/master/app/src/frontend/legend.js#L42-L55
- [ ] corresponding map style in backend: https://github.com/tomalrussell/colouring-london/blob/master/app/map_styles/polygon.xml#L64-L101
- [ ] drop cache and re-seed on live site

**Comment by martin-dj** [comment]
Changes made to the following source files:

`app/src/frontend/legend.js` 
`app/map_styles/polygon.xml`

to address this issue (#144).

**Comment by tomalrussell** [comment]
Closed by #255
