### ISSUE TITLE
Swap position of ' More about' on toolbar with 'Building categories' & rename latter

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#146]
Hi Tom I think it's best if we change 'Building categories' to ' Data categories' and put this on toolbar straight after Hello'. Then move the ' More about' category to where 'Building categories was - as tons of text in this one.

**Comment by martin-dj** [comment]
Submitted feature branch` feature/swap_positions_on_navbar` which changes the order of the nav bar items as directed, as well as changing the text from 'Building categories' to 'Data categories'.

**Comment by tomalrussell** [comment]
Closed by #253
