### ISSUE TITLE
Remove doubling up of text on landing page

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#149]
Hi tom on the new white landing page we have the same text as on the map landing page.  If we need the white first page, can you remove the text from the map landing page as otherwise they have to read it twice?  This means that that the map landing page would just have the ' Welcome to colouring london'  plus the box saying 'start colouring here'.  If you think problem just drop me an email.
PS I am removing pictures from the mobile version of wix pages today as they are taking so long to load.

**Comment by tomalrussell** [comment]
Will be fixed when we drop the `beta` subdomain and lose the white landing page - the map landing page will be the only one.
