### ISSUE TITLE
freezing building location subcategories

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#153]
Hi Tom this goes with accompanying email.
Can we as a high priority 
a) put a notice on ' Building Name' saying 'not currently active please add building number below' 
b) Make 'Building Number' and all the coordinate categories  ie OSM ID, TOID etc numeric only (probably are already)
c) Make 'Post code' so it can only have a maximum of 7 alphanumeric characters (if 7 is max number on all post codes-
d) Pre-fill London and make it uneditable
e) Remove 'Address Line 2'
f) Think of a way of  how we could prefill all streets.  Can we do this with OS Open Map Local?

**Comment by tomalrussell** [comment]
Closed by e01589b4e599ddc4accbda8ed8c7a78e11904cd7, created #184 and #186 to track data analysis/database tasks
