### ISSUE TITLE
Site has ? on google search

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#157]
can we get a tick rather than ? on google search

**Comment by tomalrussell** [comment]
Copying in notes on progress here - this is likely from a Norton or McAfee safe-search plugin.

Looks okay for McAfee: http://www.siteadvisor.com/sitereport.html?url=https://colouring.london

Requested a review from Norton but currently showing as  'untested' https://nortonsafe.search.ask.com/web?q=colouring+london

**Comment by polly64** [comment]
can u possibly request from norton again


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________

**Comment by dominijk** [comment]
Now showing as ticked for full http://colouringlondon.org/ on Norton

**Comment by dominijk** [comment]
I don't see the question mark in my search but I don't get that anyway @polly64 can you check and see if this now green for the full address

**Comment by dominijk** [comment]
Maybe separate issue but beta connection is shown as secure as below
<img width="590" alt="Screen Shot 2019-07-01 at 18 15 49" src="https://user-images.githubusercontent.com/6041913/60454678-57614f80-9c2c-11e9-9c99-63f4ccd55d29.png">


but main site is not 

<img width="739" alt="Screen Shot 2019-07-01 at 18 15 36" src="https://user-images.githubusercontent.com/6041913/60454687-5e885d80-9c2c-11e9-8be1-0a161057e33c.png">

**Comment by tomalrussell** [comment]
The 'Not Secure' connection is fixed by http > https redirects.

colouring.london looks good in Norton safe search now - @polly64 can you confirm and close this?
