### ISSUE TITLE
Add verification, and alert buttons

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#158]

**Comment by polly64** [comment]
Starting Somers Town community programme would be good to have verification button to test.
Adding to your and Dom's thoughts re verification shall we try in first instance

verification button - just a tick in a box like ' like me' to get up asap as verification the thing everything asking about - could we get this up for 'Age' and 'Storeys' in next couple of weeks?

then later as next step do a graded colour box in same way as 'like me?'

Also as you suggested add an alert button -

have i forgotten anything from our talk before?

**Comment by tomalrussell** [comment]
Duplicate of #199
