### ISSUE TITLE
aggregate colour as you zoom out

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#163]

**Comment by tomalrussell** [comment]
There could be two aspects to this - visualisation and data.

Data aggregation to larger polygons - see #170 for notes.

Visualisation
- could visualise buildings as polygons without aggregation, showing full detail at low zoom level
- could visualise buildings as points
  - either without aggregation, possibly some overlap
  - or by dropping detail in the densest areas, retaining a (representative?) sample
- could visualise at block level, based on aggregation to blocks

My intuition is that we can go a long way towards producing maps with fantastic detail without aggregation, using the building polygons - enabled by some smart tile caching and regeneration.
