### ISSUE TITLE
Add wall and roof material data fields

### ISSUE THREAD

**Issue by urbandataanalysts** [tomalrussell/colouring-london#168]
@tomalrussell As part of the listed buildings data cache we now have information on age, wall material, and roof material. Potentially address once #167 is resolved. If I understand the structure then I would do this by adding `007.construction.up.sql` and `008.age.up.sql` in `migrations` having confirmed categories with @polly64 from https://www.pages.colouring.london/buildingcategories

**Comment by tomalrussell** [comment]
That's useful, great.

Yes, adding to `migrations` is the place to add to the database. 

Age (core and facade date estimates+bounds+sources) are already in [004.location-date-size-like.up.sql#L28-L52](https://github.com/tomalrussell/colouring-london/blob/master/migrations/004.location-date-size-like.up.sql#L28-L52)

**Comment by dominijk** [comment]
Closing in favour of #359
