### ISSUE TITLE
Tweak design and change 'location' map style 

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#169]
a) Make title a couple of points larger larger -View maps is nearly same size at moment at category names
b) Make summary text under categories a couple of points smaller as want categories to stand out

c) Make 'More info' on the category page into just ' Info'  - this makes clearer and will give a margin along right hand side of column which we need as looks a bit squashed( the PR person Velvet  said she thought this meant about the project as a whole as it was like  'more about' on toolbar
d) Move 'More'about' on toolbar to the end of line so it's before 'discuss'

e) Shrink colour key and lift up page so you don't have to scroll down 

f)Because a lot of people have no said this  is confusing we need to:

Reverse key on 'Location' and remove lightest colour- so our lightest colour is very clear.

And On the key put

Title saying  Location data

Subtitle saying: 'What % of our location data have we collected?  
Add 20%,40%,60%.80%, 100% next to each category

**Comment by tomalrussell** [comment]
Closed by 7ca7fb59acd67e2090f4671008469ef2a2175443 and previous
