### ISSUE TITLE
change legend on size and shape to 'Number of storeys'

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#179]

**Comment by tomalrussell** [comment]
Problem shows up here: https://beta.colouringlondon.org/view/size.html

![image](https://user-images.githubusercontent.com/2762769/53800557-edae8e80-3f34-11e9-8e30-31b6c3909bd3.png)

Fix should be in config dict: https://github.com/tomalrussell/colouring-london/blob/master/app/src/frontend/legend.js#L43

**Comment by martin-dj** [comment]
Fix submitted to feature branch and pull request opened.

**Comment by tomalrussell** [comment]
Closed by #226
