### ISSUE TITLE
add boxes for all data subcategories on the View building page

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#180]

**Comment by tomalrussell** [comment]
Is this to change design/presentation (similar to #178)? Or is this to add data fields and headings for all remaining categories and subcategories (Greenery, Use, and the rest)?

**Comment by polly64** [comment]
Yes sorry this is same add same style boxes to all subcategories available in View building mode

Polly Hudson
Doctoral researcher (EPSRC DTG)
Bartlett Centre for Advanced Spatial Analysis
University College London
90 Tottenham Court Road W1T 4TJ


________________________________

**Comment by tomalrussell** [comment]
Great - closing this in favour of #178 (which is on the to-do board)
