### ISSUE TITLE
Notes on remaining category uploads

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#188]
Hi Tom good to see you, when do you want to upload the next category? 

This is in order of easiness (I think).  The subcategories may change a bit as people comment, but  good to get up main framework and understand which subs we want to visualise.  Also we really want  a format for  each to add
a) source 
b) verification (i.e. 'click here to verify this information is correct' - i click per user per entry) for each one.
So suggest-

       1. Sustainability - you could add just EPC, DEC, BREAM for this - we can prefill BREAM. I will send you BRE contact via email. Ignore other subcats in this one for now
           
      2. Greenery - pretty straight forward but let me know if queries

   3. Demolition and demolition history - this is a really interesting one, good and controversial - only needs 3 very bright colours in key , (i. proposed demolition ii. approved/pending , and for pending demolition, iii) Demolition history).  the first two colours would override the 3rd.   Here we also need to have a way, when the  building is moving from 
proposed-pending (i.e. approved planning)- demolished to clear each previous box. The building of course may go from proposed to nothing if the community fights it/application is withdrawn
We also need the demolition history pairs here done in a way you can easily insert a new pair inbetween two others, or shift the whole lot done fro recent demolitions. 

     4. Construction - quite straightforward i just need to run categories past UCL Energy first

     5. Team - text based category so we can load up but just need to block additions until we've thought through security

     6. Land use and Building type- these go together -  I will get on the case with this one when Martin starts - I probably need to set aside 3 days for this one

**Comment by tomalrussell** [comment]
Closing - enabling each category is tracked separately.
