### ISSUE TITLE
increase number of likes on like me key and change strapline

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#189]
a) an amenity society in islington is going to test the like me section to demonstrate community concern at the potential demolition of a local building.  Can we up the top amount to 100? and then do <5, 5-19 20-49 50-99 and > 100 perhaps?  
b)  Also Issue 122 still occurring
c)  Also can we have the hint sentence in a box below the  'I like this building' tick box ( i.e. where the - this takes time to colour sign is)?  So you're being asked explicitly 'Do you like this building and think it contributes to the city?'
d) Ideally you would be able to see colour change every like added - need way of thanking/motivating if intervals

**Comment by dominijk** [comment]
From meeting on 5th June, when using multi-select to like builds then click once means like click again means cancel that

**Comment by polly64** [comment]
.. also we need text to tell user they can 'click again to cancel'

**Comment by mz8i** [comment]
Added PR #479 changing the scale.
Re the info box with the question, the text next to the like checkbox already says "I like this building and I think it contributes to the city!" - is that sufficient or do we want an additional box with the question?
Re "click again to cancel" functionality this is not currently implemented, I'd suggest we create a separate issue for that.
