### ISSUE TITLE
Land use categories and dropdowns excel sheet

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#212]
I attach proposed land use categories which we need to get up as soon as we can for testing.  There is no perfect land use classification.  This is largely based on the National Land Use Database classification but also checked against Valuation Office Agency system.  There appears to an inherent bias in both  -these systems towards commercial rather than cultural and community uses, the latter being far less clearly defined.  I have attempted to redress this by expanding dropdown categories for two areas- a) Places of worship b) Manufacturing which I have split into factorymade and handmade.  For Retail I have called this Retail (incl.High street services) and  have included banks and building societies which NLUD separates out.  I can't see why these should be seen as different to any other services.

Before getting to the dropdowns we need to have a choice of a) single use b) mixed use.  If mixed use is chosen then it would be good to get the position as well so this divides into
What is use the Top floor/attic?
What is main use on Middle floors?
What is use on Ground Floor?
What is use in Basement?

Most mixed use and commercial use will be clustered along historical routes/ie at the historic core or along major roads out of London (though some will also occur at block corners within residential areas where pubs/cafes with flats above may be found I imagine mixed use will comprise about 7% of the stock the rest being pure residential. 

In each we need an option for other

[Land use subcategories March 1 2019.xlsx](https://github.com/tomalrussell/colouring-london/files/2923121/Land.use.subcategories.March.1.2019.xlsx)

**Comment by dominijk** [comment]
@polly64 I think this is superseded in place of what we've discussed over the past weeks. User flow is now;

- Is building single or mixed use?
- If mixed use user is prompted for number of different uses and then inputs these based on the NLUD list
- Else if only one use same selection of NLUD options

If that is correct let me know and I'll close this issue

**Comment by polly64** [comment]
yes correct


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________

**Comment by polly64** [comment]
Dom can we start this category with 
Is it pure residential? pure non-residential? or mixed use? to this category start with? This would mean that we could immediately prepopulate these in 3 colours if we were ever permitted to use the energy data (instead of having is it single or mixed use?
Also do you think we can access the above data or are there restrictions?
