### ISSUE TITLE
All subcategories excel file for timetabling

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#213]
Attach a list of all sub categories we need to upload.  These may of course require adjustments as feedback occurs.  We need to timetable these asap- I have included order of priority. Ideally initially one day to set be aside per week for Martin and I to work through these systematically including adding verification buttons.

[Subcategory list draft March 1.xlsx](https://github.com/tomalrussell/colouring-london/files/2923149/Subcategory.list.draft.March.1.xlsx)

**Comment by dominijk** [comment]
This file has been superseded by the `CL_Sub category notes pollymeet.xlsx` file in the team OneDrive linked to the slack channel. Issue closed as category and sub category additions now split into separate issues.
