### ISSUE TITLE
Sutton conservation areas

### ISSUE THREAD

**Issue by urbandataanalysts** [tomalrussell/colouring-london#214]
Found via FOI response, but restricted licence.

https://www.whatdotheyknow.com/request/conservation_area_polygons_2https://www.whatdotheyknow.com/request/conservation_area_polygons_2

Licensed under PSMA;

> This data is made freely available to other authorities under PSMA 
licensing conditions or to the public for non-commercial use only. 
You are free to use any information supplied to you for your own 
non-commercial purposes. However re-use, of the information or issuing 
copies to the public will require the permission of London Borough of 
Sutton.

**Comment by polly64** [comment]
many thanks for this.  Shapefile just sent by LB Sutton. LB Sutton has confirmed its understanding these will be released as open data. Our terms allow for 3rd party commercial use. However I will double check this with them.

[Conservation Areas.zip](https://github.com/tomalrussell/colouring-london/files/2927280/Conservation.Areas.zip)

**Comment by polly64** [comment]
Many thanks for this. LB Sutton has just sent us a shapefile through which we'll upload soon. The data can be used for third party use. However until OSMM is full opened up by the Treasury we are unfortunately subject to  restrictions on geometry/location release https://www.pages.colouring.london/location.
