### ISSUE TITLE
Colouring disappears on some where age just been coloured as u zoom out

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#219]
Coloured 'Here east' building E20 2ST. Delay on colouring (though not when a did a small building number of storeys just before). Then coloured but when I zoom out lose colour though it can be seen on nearby buildings filled in at another time,

**Comment by tomalrussell** [comment]
This is expected behaviour for the moment - work still in progress on #85 - low-zoom tiles are cached for too long.
