### ISSUE TITLE
Spatial analyis of building connectivity

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#22]
Classify buildings as one of {end-terrace, mid-terrace, semi-detached, detached, unknown} from their geometry and spatial relations.

**Comment by dominijk** [comment]
As discussed with @polly64  UCL Energy have undertaken this already linked to UPRN, @dominijk to discuss if they would like to add their data to the map

**Comment by tomalrussell** [comment]
See also https://github.com/geospatialncl/uk_building_classification_nismod-db for similar analysis.
