### ISSUE TITLE
Building height data

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#222]
**Easy quick option** use EMU data pack for LIDAR derived building height data and credit them. **NOTE** This is for built blocks (not individual buildings and is made using OS Open Local) They release under CC 4.0 which allows;

> Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material
> for any purpose, even commercially

https://certificates.theodi.org/en/datasets/213432/certificate

**Slower option** run the analysis to make our [own](http://blog.nadnerb.co.uk/?p=209). @polly64

**Comment by dominijk** [comment]
Relates to #194. Discussions with UCL Energy to use their data

**Comment by tomalrussell** [comment]
Let's close this idea in favour of possible UCL Energy dataset.
