### ISSUE TITLE
Is it possible to use Gill sans font throughout?

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#244]
- v similar to what we have now - just means consistent with logo

**Comment by tomalrussell** [comment]
We decided against this previously, and I would strongly recommend against it: the font used in the logo is suitable for the logo as a display font, but is not ideal for body text, labels or user-interface controls, especially at the range of sizes and weights that we use.

**Comment by tomalrussell** [comment]
Closing this in favour of keeping standard sans-serifs - should be a plus for performance and flexibility, hopefully isn't too much of a compromise on style :bowtie:
