### ISSUE TITLE
landing page text correction

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#254]
Hi Tom when we met we shortened the landing page text by taking out CASA but we actually need to keep this in at the moment and also to make this 'The Bartlett Centre for Advanced Spatial Analysis'.   Can you also make the next sentence read 'Can you help us? We're still at an early stage of development, and we're looking for volunteers of all ages and abilities to test and feedback on the site as we build it.'

This makes it clear from the outset that we're very much under construction. Thanks Tom

**Comment by tomalrussell** [comment]
Closed by 47f8109d34ff6124c04f9c6680f7813981dfd7a5
