### ISSUE TITLE
Change the title  'Use' to 'Use and Type' on main categories

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#265]
All wix pages have now been changes to include ownership and to merge Use and Type

**Comment by dominijk** [comment]
@polly64 Can I check on `Ownership` category, it's not in the 12 listed on the WIX which also shows  `Land Use` and `Type` as separate categories .

**Comment by polly64** [comment]
under Community - changed in order minimise privacy fears but keep collecting what we always wanted to collect- also like having the word community as a category title


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________
