### ISSUE TITLE
problem with overlapping search for postcode button

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#268]

**Comment by dominijk** [comment]
Links to #269 , quick fix is rename as `Postcode search` or 
- Find postcode
- Enter postcode 

in place of `Search for a postcode` as below;

<img width="791" alt="Screen Shot 2019-07-01 at 17 41 19" src="https://user-images.githubusercontent.com/6041913/60452888-87f2ba80-9c27-11e9-816b-de939f08d607.png">

**Comment by dominijk** [comment]
Duplicate of  #276 (fixed)
