### ISSUE TITLE
data ethics section

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#271]
Hi Tom I've begun to draft a data ethics section based on the ODI's 15 data ethics canvas questions.  You can access it through the Wix link.  It's a very rough draft at the moment but it's a very useful frameowrk for us. Could you add or correct any obvious stuff and then I'll finalise and we can upload onto the site and have it as a live working document .

We also may want to group this with other items in a dropdown on the toolbar though I also like the idea of having this right up there as a priority

- [x] Update live document
- [x] Copy to WIX site

**Comment by tomalrussell** [comment]
Looks good so far - we've got #380 outstanding to review again, so I'll close this.
