### ISSUE TITLE
Main menu expand/collapse on mobile

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#272]
Menu in header should expand/collapse at small screen sizes

See https://getbootstrap.com/docs/4.0/components/navbar/#responsive-behaviors for bootsrap helper classes (.navbar-collapse...)

Consider:
- making the navigation menu full screen height when visible, hidden by default
- keeping the colour-changing logo visible top-left, over the map
- click logo to show menu, logo remains in place, white-background menu appears from left

**Comment by martin-dj** [comment]
I believe the Bootstrap CSS classes require JQuery to respond to button clicks to expand/collapse the menu. Is it OK (and sufficient?) to add JQuery to the list of dependencies (package.json)?

**Comment by tomalrussell** [comment]
I'd avoid the jQuery dependency and use react to conditionally include the classes in response to click events, maintaining a little state local to the component: https://reactjs.org/docs/handling-events.html

**Comment by tomalrussell** [comment]
Closed by #279
