### ISSUE TITLE
Legend should not obscure map on mobile

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#274]
Any thoughts on best design approach?
- expand/collapse legend, default to collapsed on mobile (i.e. only the grey colouring london logo and legend heading and small arrow ('Age ^') visible in collapsed mode
- incorporate legend into right-sidebar pull-in?

**Comment by martin-dj** [comment]
Hi Tom,
I've been looking at the first approach (expand/collapse legend) and have made some progress using the Bootstrap `collapse` class, along with a `React component` subclass to store state and respond to `button` ('Age ^') clicks to expand/collapse the list.

However, currently the button is always present (regardless of screen size) and the default state is collapsed (for the mobile view) set in the `React component` subclass constructor.

i) Presumably, I can use a media request and some CSS to hide the button for large screens?

ii) Is there an elegant way to detect the screen size (or media state) in the `React component
` constructor to set the state accordingly (collapsed for mobile/expanded for large screens). Or is there a better way to achieve this?

Martin

[legend_responsive.txt](https://github.com/tomalrussell/colouring-london/files/3258304/legend_responsive.txt)

**Comment by tomalrussell** [comment]
Something like this should do the trick - 

```javascript
constructor(props) {
  super(props);
  this.state = { collapseList: true };
  this.onResize= this.onResize.bind(this);
  if (window && window.innerWidth) {
    // if we're in the browser, pass in as though from event to initialise
    this.onResize({target: window});      
  }
}

componentDidMount() {  
  window.addEventListener('resize', this.onResize);
}

componentWillUnmount() {
  window.removeEventListener('resize', this.onResize);
}

onResize(e) {
  this.setState({collapseList: (e.target.innerWidth > 968)});  // magic number for window width 
}
```

**Comment by martin-dj** [comment]
Thanks, I'll try that out.

**Comment by martin-dj** [comment]
Have implemented an expandable/collapsible legend for small screen sizes. The legend itself seems to work as desired. However, the position of the legend for mobile phone screens needs further attention (to the CSS). 

For a mobile phone sized screen CSS `bottom` lies below the viewable portion of the screen, which is leading to undesirable positioning of the legend on mobile phone sized screens. I guess this relates to the parent CSS? Any thoughts would be welcome.

**Comment by martin-dj** [comment]
For small screens the legend is positioned (`bottom:50%`) just above the info-container (for the 'sidebar' content).  

For wider screens which adopt the normal layout (sidebar at the side) the legend adopts its normal position just above the bottom of the screen.

This approach avoids widespread CSS changes to other components.
