### ISSUE TITLE
'Click to edit' notice on mobile

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#275]
'Click to edit' prompt is helpful but should also not obscure the map - could include on mobile inside the bottom-half "sidebar" space?

**Comment by martin-dj** [comment]
I've been looking at issue #138 (Just enough mobile layout) over the last few days and in light of this I must say I'd be inclined to hide this on small screens (mobile). For mobile screens (as opposed to tablets) less is more.

What are your thoughts Tom?

**Comment by martin-dj** [comment]
Addressed this issue in feature branch `feature/search_postcode_on_mobile`.
