### ISSUE TITLE
Search postcode on mobile

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#276]
Postcode search should be accessible at small screen sizes - consider:
- top-level menu entry for 'search' which shows search view 
- or expand/collapse from search icon (collapsed view is just icon, located under the +/- zoom buttons, expanded view is full width search box + icon).

**Comment by martin-dj** [comment]
Implemented an expand/collapse search icon in feature branch `feature/search_postcode_on_mobile`.

Also addressed issue #275 Click to edit' notice on mobile as this is related.
