### ISSUE TITLE
allow main age copy tool to copy all items 

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#282]
Hi Tom can you change the top copy button on age category to ' Copy all' and let it copy all the subcategory data ( e.g source, earliest start date etc as they will all usually be exactly the same , thanks!
Also when I add date the building colours but no colour when i add other stuff so hard to see if added. When i try and copy the source after ive coloured it doesn't seem to copy. i don't seem to be able to save it?

**Comment by dominijk** [comment]
@tomalrussell Is this a `top-level` change?
