### ISSUE TITLE
Duplicate user names

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#286]
I registered on desktop at casa with casa_demonstration as a user name, I then entered the same details in laptop and it didn't recognise them. I then registered on the laptop under the same username and it accepted the registration. This means there should be two users names registered as casa_demonstration one with an email address attached one without

**Comment by tomalrussell** [comment]
One user is registered as `casa_demonstration` and another as `casa_demonstration ` (with final space).

We could ensure usernames only include some subset of characters -  `[a-zA-Z0-9_-]`? - what do you think?

**Comment by dominijk** [comment]
Ahh, user error! I think restrict to alpha numeric and one or two special is good solution, to stop people like me doing something stupid

**Comment by mz8i** [comment]
Resolved by adding username validation and restricting to alphanumeric + underscore (#424)
