### ISSUE TITLE
Comments on including what3words.com?

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#293]
Can I have your comments on including what3words references as an option in the Location category?

**Comment by dominijk** [comment]
I'd need to look at their docs but I don't think it's open source, so even if someone gives us the what 3 words then we won't get the lat long from it.

**Comment by tomalrussell** [comment]
Looks fairly limited - their API will offer the conversion, but:

> You must not pre-fetch, cache, index, copy, re-utilise, extract, store (including in a database) or utilise any what3words Data in any way that means you are effectively circumventing making an API Request or a third party making an API Request (including any potential API Requests)
https://what3words.com/developers/api-licence-agreement/

**Comment by polly64** [comment]
Ok so we won't use it thanks
