### ISSUE TITLE
Github: Admin

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#303]
@tomalrussell 
1. Does the `Awesome community` milestone make more sense as a project or label? 
2. Similar to above, does a project or label make sense for `mobile` and `API` deliverables?
3. Can we add the [user](https://github.com/colouringLondon-FrontEnd) `colouringLondon-FrontEnd` to the repo so issues can be assigned to the new member for when they join, can then be self assigned by that person

**Comment by tomalrussell** [comment]
1. I've made 'Awesome community' a `ui:community` label and closed the milestone
2. Mobile design/ux improvements and API - I've created `ui:mobile` and `api` labels
3. let's find out Maciej's username and skip straight to assigning to him next week
