### ISSUE TITLE
Sustainability contact

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#313]
From excel file

Write to John Tracey Smith re: Sustainability category 

@polly64 will you email me details on this or this is one you're working on already?

**Comment by polly64** [comment]
hello



Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________
