### ISSUE TITLE
contributor-agreement 404

### ISSUE THREAD

**Issue by kekscom** [tomalrussell/colouring-london#317]
the information is not accessible during sign up

**Comment by dominijk** [comment]
@kekscom Thanks for the note, we'll fix that this week

**Comment by dominijk** [comment]
See #48

**Comment by tomalrussell** [comment]
- [ ] Change link to ...contributor-agreement.html
- [ ] Check with @martin-dj on status of contributor agreement text
- [ ] Create page with placeholder ("Contributor agreement - coming soon") or draft text
