### ISSUE TITLE
UI: Privacy-policy

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#323]
As #317 link returns `Cannot GET /privacy-policy` @tomalrussell is there content for this and just broken link? Did you have a UI/UX in mind for these (new tab or pop up modal?). I'd go with a modal and link to the ethics section on the WIX for now.

**Comment by tomalrussell** [comment]
- [ ] Fix 404 error to render a page with main menu and show message (like *.html 404 e.g. https://beta.colouring.london/privacy-policy.html)
- [ ] Change link to https://beta.colouring.london/privacy-policy.html
- [ ] Check with @martin-dj on status of text.
- [ ] Create page with placeholder ("Privacy policy - coming soon") or current draft text

**Comment by mz8i** [comment]
@tomalrussell need some clarification:
Re TODO 1. so we want a generic 404 page set up server-side for the routes not ending with *.html, but it should be basically the same as the *.html one, is that correct?

Additionally, there is both policy and contributor agreement missing, so I assume TODOs 1-3 apply to both, separately?

**Comment by tomalrussell** [comment]
@mz8i yes, I think we should have a generic 404 to catch any unhandled 404s, and the *.html one seems good. 

The only exception would be JSON routes (essentially the API `/building` and friends), which might return JSON with an error field as well as the 404 code. They would currently return an empty response, which I think is okay too.

And yes, I think there are draft texts for both pages floating around. The TODOs for this issue and #317 are identical up to the name and content of the page (sorry, should have flagged that before).

**Comment by mz8i** [comment]
@tomalrussell would it be appropriate for the JSON API to sit under its own nested route, like `/api`? Right now there's maybe a lack of clear separation between frontend and API.
The main point is that, for a route `beta.colouring.london/some-route` (without `.html`) - is that a frontend route or an API route?
The proposed structure would be
- `/tiles` for the tileserver
- `/api` for the data JSON API - 404 on any sub-route potentially returns an error JSON rather than a webpage
- everything else (`/`, `/*.html`) for the frontend - returning 404 html page on not found

**Comment by martin-dj** [comment]
### Draft Colouring London Privacy Policy
This privacy policy explains how Colouring London uses the personal data we collect from you when you use our website. Colouring London is a research project developed by the Bartlett Centre for Advanced Spatial Analysis (CASA) at UCL. Colouring London is registered for data protection purposes with the UCL data protection office.

 **What data do we collect?**
Colouring London collects the following personal data:
A username and email address. We recommend you do not use your actual name for your username. We also collect your password, which is stored as a cryptographic hash unique to Colouring London.

**How do we collect your data?**
You provide Colouring London with a minimal amount of personal data when you register with the website and accepts the terms and conditions including this privacy policy.

**What purposes do we use your data?**
Colouring London uses your personal data to enable you to login to access and contribute to the Colouring London project and to provide a personalised user experience when you are logged in. We will not share your personal data (such as your email address) with any other parties or use your personal data for any purposes other than the Colouring London project.

**What is the legal basis for processing your data?**
Data protection laws require us to meet certain conditions before we are allowed to use your data in the manner described in this notice, including having a ‘legal basis’ for the processing. Colouring London, as a research project, is processing your personal data in pursuance of performing a task in the public interest. For further details on the ‘public task’ legal basis for processing, please see UCL’s Statement of Tasks in the Public Interest, available [here](https://www.ucl.ac.uk/legal-services/sites/legal-services/files/ucl_statement_of_tasks_in_the_public_interest_-_august_2018.pdf) 

**How do we store your data?**
Colouring London stores your data at UCL in London behind the organisation’s firewall in a secure database using industry standard practices.

**How do we use cookies?**
Colouring London only uses cookies to improve the user experience of users of the website, for example we use cookies to keep you signed in. We do not use cookies for marketing or advertising purposes.

**What are your data protection rights?**
Under the General Data Protection Regulation, you have certain individual rights in relation to the personal information we hold about you. For the purposes of research where such individual rights would seriously impair research outcomes, such rights are limited. However, subject to certain conditions, you have the following rights in relation to your personal data:
 
• A right to access personal data held by us about you.

• A right to require us to rectify any inaccurate personal data held by us about you.

• A right to require us to erase personal data held by us about you. This right will only apply where, for example, we no longer need to use the personal data to achieve the purpose we collected it for.

• A right to restrict our processing of personal data held by us about you. This right will only apply where, for example, you dispute the accuracy of the personal data held by us; or where you would have the right to require us to erase the personal data but would prefer that our processing is restricted instead; or where we no longer need to use the personal data to achieve the purpose we collected it for, but we require the data for the purposes of dealing with legal claims.

• A right to receive personal data, which you have provided to us, in a structured, commonly used and machine-readable format. You also have the right to require us to transfer this personal data to another organisation.

• A right to object to our processing of personal data held by us about you.

• A right to withdraw your consent, where we are relying on it to use your personal
data.

• A right to ask us not to use information about you in a way that allows computers to make decisions about you and ask us to stop.

It is important to understand that the extent to which these rights apply to research will vary and that in some circumstances your rights may be restricted. If you notify us (using the contact details set out below) that you wish to exercise any of the above rights and it is considered necessary to refuse to comply with any of your individual rights, you will be informed of the decision within one month and you also have the right to complain about our decision to the Information Commissioner’s Office.

Please also note that we can only comply with a request to exercise your rights during the period for which we hold personal information about you. If that information has been irreversibly anonymised and has become part of the research data set, it will no longer be possible for us to access your personal information.

**Changes to this privacy policy**
Changes to this privacy policy will be notified via the Colouring London website. This privacy policy was last updated on 13 August 2019.

**Who do I contact with questions?**
If you have any questions about your personal data and Colouring London that are not answered by this privacy notice then please consult UCL's data protection web pages here, where further guidance and relevant UCL policy documentation can be found.

If you need further assistance in the first instance, please email casa@ucl.ac.uk . If you wish to complain about our use of your personal data or exercise any of your rights, please contact UCL's Data Protection Officer: data-protection@ucl.ac.uk or Data Protection Officer, UCL Gower Street, London WC1E 6BT.

If we are unable to adequately address any concerns you may have about the way in which we use your data, you have the right to lodge a formal complaint with the UK Information Commissioner's Office. Full details may be accessed on the complaints section of the Information Commissioner's Office [website](https://ico.org.uk).
