### ISSUE TITLE
Unable to log in to CL website after importing database dump into CASA server

### ISSUE THREAD

**Issue by martin-dj** [tomalrussell/colouring-london#333]
Unable to log in to the colouring london website running off the CASA server after importing a database dump from the Azure live server. The website displays message "Must be logged". 

I'm guessing that the user was logged in on the live server when the database was dumped and this is causing an inconsistency with the state of the new server instance.

**Comment by tomalrussell** [comment]
Ideas for lines of enquiry:
- Session state is stored in the `user_sessions` table - is there anything relevant for the given user there?
- Could check that hashed/salted password is restored as expected by querying directly against the database - `SELECT user_id, (pass = crypt('thepassword', pass)) AS auth_ok FROM users WHERE username = 'theusername';`

**Comment by martin-dj** [comment]
The root cause of the issue is logging in over HTTP rather than HTTPS.  

It looks like this code snippet from `server.js`
```
if (server.get('env') === 'production') {
    // trust first proxy
    server.set('trust proxy', 1)
    // serve secure cookies
    sess.cookie.secure = true
}
server.use(session(sess));

```
prevents a session being established resulting in the error message observed (see below):

```
// GET own user info
server.get('/users/me', function (req, res) {
    if (!req.session.user_id) {
        res.send({ error: 'Must be logged in' });
        return
    }
...
}
```

Changing the `ecosystem.config ``NODE_ENV` value to 'development' resolves the issue.

Once the server is relocated to its permanent location (8/08/19) it will be allocated a static IP address and it will be possible to set up SSL properly.

**Comment by martin-dj** [comment]
Issue resolved once HTTPS set up using a self-signed certificate (with `NODE_ENV `set to 'production').
