### ISSUE TITLE
Mobile specific design review

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#334]
What's needed for high quality mobile (and mid-size - tablet) view?

Aim to focus activities - do one thing at once

Key for launch
- [x] sign up flow must work on mobile
- [x] fullscreen activities: select category <> view/edit data <> view/navigate map

Nice to have
- [ ] go to my location button,  ie. I'm out and about and want to edit the building I'm stood by, interface jumps me to this position on the map
- [ ] swipe between categories (category header on map and data views?)

Edit this issue to create TODO list

**Comment by dominijk** [comment]
In terms of October launch what would you think is key? Resolving signup so people can join in the night would be top for me and then making viewing map as large as possible.

**Comment by tomalrussell** [comment]
Just re-edited - what do you think?

**Comment by dominijk** [comment]
I'd say that's good approach for launch, but don't have a handle on how much work that is as I've not made a mobile optimised web app before, it doesn't sound that complex. A small tablet / phone will never be the best way to input data given the screen size so I see this as more of an edit of existing entries tool. @adamdennett Did we have any feedback on how schools will access the platform, will they be inputting from the field on devices?

**Comment by tomalrussell** [comment]
Closing this as mobile seems good-enough following #403. Will open separate issue for location button.
