### ISSUE TITLE
Map: Add GLA boundary to site

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#335]
As discussed at meeting 1st Aug 2019, this will be a GeoJSON object. @tomalrussell  There are two file options for this  

- [ ] Simplified file (48kb) as stored in [repo](https://github.com/tomalrussell/colouring-london/blob/master/docs/GLA_BoundaryWGS84.geojson)
- [ ] Full [resolution](https://data.cdrc.ac.uk/dataset/london) file (279kb)

**Comment by mz8i** [comment]
Feature completed, need follow-up work on including attribution
