### ISSUE TITLE
Server: Ensure site is robust enough for anticipated flows for large-scale publicity 

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#339]
- [x] Run tests to answer questions:
  - How many user can be concurrently viewing?
  - How many user can be concurrently editting?

**Comment by martin-dj** [comment]
Undertook load testing using JMeter against clstaging (currently configured identically to clproduction) with rate limiting disabled.

One iteration of The test plan involved:
100 thread (users) performing a GET against /view/location.html ramping up over 10 seconds.
100 thread (users) performing a GET against /view/age.html ramping up over 10 seconds.
100 thread (users) performing a GET against /view/size.html ramping up over 10 seconds.

A forever loop was used with the test plan being manually stopped.

This resulted in approximately 380 requests per second and some 20,000 requests per minute.
The average request response time was 740 msec.
No errors were observed.
The site remained useable for a human user.
CPU usage of the 6 processors allocated was nearing 100% according to mpstat.
Memory usage was about 1 GB
No errors were detected in the test results.

**Comment by tomalrussell** [comment]
That sounds promising. 

Can you run a test plan to experiment with the tileserver responses for a couple of zoom levels and tilesets?

- `/tiles/date_year/17/65485/43579.png`
- `/tiles/size_storeys/17/65485/43579.png`
- `/tiles/date_year/10/511/340.png`
- `/tiles/size_storeys/10/511/340.png`

**Comment by tomalrussell** [comment]
It would be useful to understand update performance too, for edits:
- `POST /api/buildings/2464006/like.json` with JSON body `{"like":true}` 
- `POST /api/buildings/2509730.json` with JSON body `{""location_postcode"":""NW1 6JJ""}`

These would need to be authenticated, either with api_key in URL params, or with a cookie set in the request headers. Firefox dev tools lets you "Copy as CURL", if that's helpful. Trimmed example: `curl "https://colouring.london/api/buildings/2509730.json" -H "Content-Type: application/json"  -H "Cookie: cl.session=s"replace_with_actual_cookie_value" --data "{""location_postcode"":""NW1 6JJ""}"`

**Comment by martin-dj** [comment]
**Zoom Level Testing**
Run against `clstaging` (after building tile cache). Two test plans were run at Zoom 17 and Zoom 10 respectively.

**Zoom 17**
One iteration of The test plan involved:
100 threads performing a GET against `/tiles/date_year/17/65485/43579.png` ramping up over 10 seconds.
100 threads performing a GET against `/tiles/size_storeys/17/65485/43579.png` ramping up over 10 seconds.
A forever loop was used with the test plan being manually stopped.

- This resulted in an average of 170 requests per second and some 10,000 requests per minute.
- The average request response time was about 1000 msec.
- CPU usage of the 6 processors allocated was about 80%.
- Memory usage was about 1.5 GB
- No errors were detected in the test results.


**Zoom 10**
One iteration of The test plan involved:
100 thread (users) performing a GET against `/tiles/date_year/10/511/340.png` ramping up over 10 seconds.
100 thread (users) performing a GET against `/tiles/size_storeys/10/511/340.png` ramping up over 10 seconds.
A forever loop was used with the test plan being manually stopped.

- This resulted in average of 400 requests per second and more than 20,000 requests per minute.
- The average request response time was about 400 msec.
- CPU usage of the 6 processors allocated was about 50%.
- Memory usage was about 1.5 GB.
- Some errors (about 3%) were detected in the test results (NoRouteToHost Exception), which seem to occur when the transient requests per second exceeded 450 r/s.

**Comment by martin-dj** [comment]
**Edit Testing**

Test plan ran against staging server as follows:
One iteration of The test plan involved:
100 threads performing:
 	a POST against /api/login with login credentials ramping up over 10 seconds.
	a POST against /api/buildings/2464006/like.json with payload

100 threads performing:
 	a POST against /api/login with (different) login credentials ramping up over 10 seconds.
	a POST against /api/buildings/2509730.json with payload

A forever loop was used with the test plan being manually stopped.

**Results**
- an average of 360 requests per second and in excess of 20,000 requests per minute.
- The average request response time was about 50 msec.
- CPU usage of the 6 processors allocated was about 80%.
- Memory usage was about 1.6 GB
- No errors were detected in the test output.

**Comment by tomalrussell** [comment]
Thanks - useful benchmarks, seem sufficient for anticipated load in the near future. Let's monitor and come back to elements of this as necessary.
