### ISSUE TITLE
API: Bulk download of file 

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#342]
Enable users to download simple flat file of data in CL
- [ ] extract open dataset to archive storage (current state + edit history)
- [ ] simple list-of-links page to download "Latest" and "Archive" bulk extracts

**Comment by mz8i** [comment]
@tomalrussell what format do we want to export the edit history in?
Specifically:
- do we include forward (and reverse?) patch or some other description of changes?
- for edit author, do we want user's UUID or name (potentially modified over time by user deletion)
- I assume bulk edits are split into individual building edits? Given that there's a `building_id` in `logs`

**Comment by mz8i** [comment]
On the topic of IDs / UUIDs, is there any case at all where we want to include the internal database IDs in the export files? There's many - `building_id`, `geometry_id`, `revision_id`, `building_property_id`, `log_id` etc

**Comment by tomalrussell** [comment]
Include where they're necessary for cross-reference between exported tables:
- `building_id` is essential
- `geometry_id` skip
- `revision_id` include as cross-reference to last edit in history
- `building_property_id` skip
- `log_id` include for reference by `revision_id`

**Comment by mz8i** [comment]
I'd think about renaming either `revision_id` or `log_id` - at least in the exported files. I overlooked the foreign key so didn't realise they were referring to each other, but to avoid confusion for users of the extract I'd name them the same

**Comment by mz8i** [comment]
Closed by #411
