### ISSUE TITLE
Server down: Adjust modal message

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#344]
Until server is back up, as below;

@tomalrussell I couldn't fully test this on my local VM as I don't have main page without map, but the modal message updated 

<img width="657" alt="Screen Shot 2019-08-02 at 14 31 22" src="https://user-images.githubusercontent.com/6041913/62373726-50cb3e00-b532-11e9-9001-93a9186cd216.png">

**Comment by dominijk** [comment]
@tomalrussell I've updated to revert the message back to the standard welcome

**Comment by tomalrussell** [comment]
All updated and reverted, thanks.
