### ISSUE TITLE
UI/UX: Improved user flow

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#347]
### What it does?
Streamlines the user experience by reducing step from viewing to editing. On load all
categories are collapsed to fix #278 for mobile see #272. Related to this is update of category side bar to colour the categories #285 

### Example
Remove 'view map' stage and load straight on 'view data' page. Make editing/saved feel more 
like a within-form change - active/disabled fields
### How it works
On load all categories are collapsed. On opening main category fields (sub categories which have map colours/styles attached are visible. Clicking on those; 
- Changes map style as #367 
- Loads legend 
- Prompts user to click building to view data (or preselects building and shows data?) 
- Viewing data is same appearance edit data, clicking into field data boxes will allow logged in user to edit the field or prompt user to login/sign up

### What else needs doing

- [ ] Dependency on hierarchical architecture (see #237) and declarative flow 
- [x] Dependency on declarative flow #368 
- [x] Dependency on signup process

**Comment by tomalrussell** [comment]
Closing as the majority of sub-issues are done - still tracking #237 and #367 in #299
