### ISSUE TITLE
Dom-update for comms  on launch visuals per category 

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#355]
Hi Dom could you give a quick update on primary and secondary datasets that definitely will  be visualised for in time for launch? Imagine as follows:
Location- % coverage OK - Plus add streetnames?
Land use - My land use data for camden (Tom has)  - Nicolas land use with CASS?
Building type - form - LBSM attachment? Actvity type use my camden data (Tom has)?
Age - main construction date - OK (need to add age sources for my data- Tom has)
can we add a much simpler key for century too? (21st, 201th, 19th, 18th, 17th, pre 1600)
Size and shape -  my storey data Fitzrovia OK, plus height data LBSM?
Construction?
Team - greyed out
Sustainability - DEC only?
Greenery - now street block - greenery? 
Community - local authority assets -as discussed  link Paul /GLA
Planning- conservation areas (clean up ) and Listed building samples?
Like me - OK

Think we have lost to show of interest to very wide range of audiences if we have these up. Sound about right? Just also need to update Bartlett comms

**Comment by dominijk** [comment]
@polly64 I can update on the categories that will be available to input  as I'm working through these now. In terms of bulk data that will be inputted for launch that will come later. I'm prioritising the interface and user flow first then bulk data inputs after. I'll send an email tomorrow.

**Comment by polly64** [comment]
thanks


________________________________

**Comment by dominijk** [comment]
@polly64 Reviewed as below;

- Location ✅- % coverage OK - ~~Plus add streetnames?~~ _Looking at enabling streename drop down but pre-populating streetnames is one to discuss_
- Land use ✅ - My land use data for camden (Tom has) - Nicolas land use with CASS?
- Building type ✅- form - LBSM attachment? Actvity type use my camden data (Tom has)?
- Age ✅ - main construction date - OK (need to add age sources for my data- Tom has)
- can we add a much simpler key for century too? (21st, 201th, 19th, 18th, 17th, pre 1600)
- Size and shape ✅ - my storey data Fitzrovia OK, ~~plus height data LBSM?~~ _will keep pushing for this seems to be ok with them in principle but they are now away for two weeks_
- Construction? - _Will circulate a list of categories for these if they make sense then yes_
- Team - greyed out. _Awards is a quick win to have something for this? I've asked @livyg to research a list of awards to add to drop down_
- Sustainability ✅ - DEC only? _& date of last retrofit looks an easy one to add_
- Greenery  ✅ - now street block - greenery? _@polly64 As Friday chat, for launch. Qualitative question on how people feel about the environment and bird/bat/bug boxes?, I've added these to the spreadsheet_ 
- Community ✅- local authority assets -as discussed link Paul /GLA _Tenure will be up for launch_
- Planning ✅- conservation areas (clean up ) and Listed building samples? _@polly64 I keep pushing HE on getting the licence to release this data but keep getting no answer_
- Like me ✅ - OK

**Comment by polly64** [comment]
Great dom many thanks looks really good. Re construction we could prepopulate all pre 1900 houses from my dataset as brick/ solid wall , this would give us just a nice bit of colour albeit small 

re LBs why not send another email to gill and stress issue of launch so she's aware you haven't heard and copy me in, I know they want to help on this
