### ISSUE TITLE
Update people signed up for project updates

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#36]
Can we send an email just to keep those signed up updated? ie something like 'We're still ironing out some technical issues but we're hoping to let you start viewing and editing in 2-3 weeks. To start of with we'll be testing 3 of our 12 data categories: Building Age, Building Size (number of Storeys), and 'Like me' (ie whether you like the building). We'll update you as soon as we release. Thanks again for your interest!'.

**Comment by tomalrussell** [comment]
Quick update sent: https://tinyletter.com/colouringlondon/letters/colouring-london-a-quick-update
