### ISSUE TITLE
When user not signed in, Like Me! redirects to blank page

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#364]
Steps to reproduce:
1. Sign out from the portal
2. Go to the map view
3. Select a building
4. Click on the Like Me! section in the sidebar

Actual behaviour:
Redirects user to a blank page. Only refreshing the page displays the map view again. Back button does not bring up the map.

Expected behaviour:
Should redirect to login page or display message in the sidebar that this functionality is only available for logged in users

**Comment by tomalrussell** [comment]
Closed by 7d7c22b
