### ISSUE TITLE
UI/UX: hide/show fields (was Declarative flow)

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#368]
### What it does?
If you enter one field, related fields are enabled and become visible and act as prompt to
complete the category.
### Example
Planning category; Only show 3 main fields for category, if you enter one of these others
appear based on that selection. 
### How it works
1. Click on sub category 
2. Map style changes as colour any/all see #346 
    - On save map updates, colour changes
    - Extra linked fields become visible (menu expands)
    - User can tab to next changing map style to field style, is removing colour completely or
      just changing tint. Categorical categories (age and community) more complex than location
      / like me example.

### Dependencies

#346 Colour all/any
#300 Hierarchical structure

**Comment by dominijk** [comment]
@tomalrussell Just to confirm that this is different functionally to #300

**Comment by tomalrussell** [comment]
@dominijk yes - going on the description, this is a neat top-level issue.

The words 'declarative flow' sound a bit more like the lower-level refactor of how the UI is rendered - I've created #376 for that bit of work.

**Comment by tomalrussell** [comment]
I'm actually going to close this in favour of #300 - let's nudge the UI along and fill out the remaining categories and fields before coming back to these more complex multi-stage features.
