### ISSUE TITLE
Make Nights and Day Options more obvious & create hover explanations for icons

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#37]
Can you show the words 'nightview' and 'day view' as very important users can view in both (we can't just hover on this one as too important they get it straight away.  On any other commonly used map icon that assumes you know what it is/does think we will need a hovering explanation.  Some of our users may have difficulty reading the maps without numbered buildings so anything we can do to make general experience easier to understand will help.

**Comment by tomalrussell** [comment]
Added a 'Switch theme' button:

![image](https://user-images.githubusercontent.com/2762769/45541060-e8824980-b805-11e8-9d0c-9de122fa9082.png)

![image](https://user-images.githubusercontent.com/2762769/45541076-f46e0b80-b805-11e8-9639-c32db4398788.png)


Closed by a6d1b309a44abf388ee7fd3530bfa99f862336d4
