### ISSUE TITLE
Change 'energy' category/section title to 'sustainability' 

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#371]

**Comment by mz8i** [comment]
@polly64 should I also change the description? (currently: "Are buildings energy efficient? Coming soon…")
@tomalrussell should I change the slug? (currently: "energy")

**Comment by polly64** [comment]
yes please re description if it doesn't match

**Comment by mz8i** [comment]
The above ("Are buildings energy efficient? Coming soon…") is what will currently display for Sustainability. I am assuming it's the desired description?

**Comment by polly64** [comment]
yes that's right. we need to go through all with Dom again but great for moment

**Comment by tomalrussell** [comment]
@mz8i yes, but note that the slug is referred to in a couple of places:
- [`fields-config.json`](https://github.com/tomalrussell/colouring-london/blob/95853adc57453476c2da2114ea1736faa0c57228/app/src/frontend/fields-config.json#L351)
- [`legend.tsx`](https://github.com/tomalrussell/colouring-london/blob/ab14d2af2523c6d802f895944055c60214a667df/app/src/frontend/legend.tsx#L68)
- [`sidebar.css`](https://github.com/tomalrussell/colouring-london/blob/9433fd879bb7772eb7028c285f2a5fc061a7b6c4/app/src/frontend/sidebar.css#L168)

**Comment by mz8i** [comment]
So I assume for consistency, we should also change the slugs of the fields, e.g. "energy_epc_band_current" -> "sustainability_epc_band_current" as they're all prefixed by "energy_" now.
