### ISSUE TITLE
Fix links to Planning, Community and Typology. Greenery info pages

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#372]
Hi Dom I've corrected the SEO settings for the above pages, could you possibly relink each of these 4 categories to its  'info' button on the View Map page otherwise people will be seeing an error message. Many thanks

**Comment by mz8i** [comment]
@polly64 could you please help me with the links?
So far I've established:
- Planning -> https://www.pages.colouring.london/planning
- Community -> https://www.pages.colouring.london/community
- Greenery -> https://www.pages.colouring.london/greenery
But couldn't find the appropriate page for Type - either under /type and /typology 

Also I think the links are mixed up on website (https://www.pages.colouring.london/buildingcategories) in the colourful squares: Type links to /community, Community links to /planning, Planning links to /demolitions

**Comment by mz8i** [comment]
Ah, found the Type link - /buildingtypology
I will update the links and close this issue, but please @polly64 could you take a look at the links on the website?

**Comment by polly64** [comment]
Hi I've update the links let me know if still problems
