### ISSUE TITLE
screenshots taken with no credit

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#375]
![colouring london](https://user-images.githubusercontent.com/42236514/62836425-866ed600-bc5a-11e9-83e5-b45360b774a6.JPG)

Noticed this where they have managed to screenshot the map without the key and haven't referenced the project. Let's talk about what we can do re this

**Comment by dominijk** [comment]
@polly64 We've made it difficult to do this by having the legend, but if your want to ensure you always have credit then the only way I can currently think of is applying some form of watermarking. Ultimately you will always be able to crop the image to cut out legends, footnotes and headers. 

In the above [example](https://www.levittbernstein.co.uk/now/big-data-and-the-design-of-cities-chicago-and-london/) this is more likely as the coloured map doesn't fill the screen (the map is also fairly meaningless without title/legend), it's very poor practice of them not to cite the project in the text either.

**Comment by polly64** [comment]
I'm not really keen on watermarking. I wonder if we should have a clearer note on the interface saying we ask people to ensure OS credit and CL key are included if people wish to screenshot from the site?

**Comment by dominijk** [comment]
@polly64 That sounds like a better approach. I'll have a think on where this should be, part of signup and also visible during viewing is first thought with a link back to the ethics section on why citation matters.

**Comment by polly64** [comment]
Great yes think we should do all three you suggest

**Comment by tomalrussell** [comment]
Clearer notes now on `develop` from #458
