### ISSUE TITLE
Category menu template

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#377]
![Baxtercategoryimage](https://user-images.githubusercontent.com/42236514/62856515-0ba2cb00-bced-11e9-8336-86ddec9aa4f1.jpg)

This is the main menu page from layouts done with Louis:
- it's a clear entry point, addresses the fact the jump from landing page to the maps is too big
- ignore or shorten 'How it works' text
- use updated category names
- reorder 'view maps' above 'edit maps' and link these to the view and edit pages.  
- Download would take you to the page where you can access whatever we're offering as a bulk download for the launch (#342)
- Showcase link to a Wix page (coming soon)
- When you click each of the categories this can also take you straightaway the info page for each.

**Comment by tomalrussell** [comment]
The bulk of this bit of design is also included in the wix [building categories](https://www.pages.colouring.london/buildingcategories) page.

I'm going to take a cut at the flow from Welcome splash > Category intro > Building data which takes inspiration from this and aims to simplify the jump between each level, keeping the map in view in the background at each step.

Let's also de-emphasise the difference between View and Add/edit data - if you're looking at Building data, you might toggle between view-only/copy/edit modes, but it should feel like toggling within the same screen.

**Comment by polly64** [comment]
Hi tom think good to keep difference between view and edit on the menu - even if in practice they are more interlinked.  Reason is that some people won't want to add data. They will just want to view maps and concern re having to edit some unknown thing could put them off.  (inclusive audience issues are  now included at start og data ethics page.

Also Dom can you send  Tom CL logo if he hasn't got so it can be integrated top left land corner of page - unless easier to do your end.  This is needed to emphasise the colouring London branding and shows how the category colours are mirrored  in the logo design

**Comment by polly64** [comment]
hi tom do you know when this is likely to be up and running

**Comment by tomalrussell** [comment]
Closed by #403 - adapted to keep category squares in sidebar.
