### ISSUE TITLE
UI/UX: Activate sustainability category 

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#388]
See #360 for categories enabled in db.

- No copy option for these fields 
- If DEC / BREEAM / Award field inputted source required, with verification 

**Fields on form**

Sub category | UI | Sub category | UI
-- | -- | -- | --
EPC | Inactive |   |  
DEC | Rating - Dropdown (ENUM) | Year | Numeric entry  YYYY
BREEAM | Rating - Dropdown (ENUM) | Year | Numeric entry  YYYY
Last   significant retrofit | Numeric entry  YYYY |   |  
HQM | Inactive   |   |  
Embodied   carbon estimation for typology/size | Inactive |   |  
Life   expectancy minimum | Inactive |   |  
Average   lifespan for typology | Inactive |   |  
Typical   actual  life expectancy for   typology/contstruction materials and method | Inactive |   |  
Adaptability/repairability  rating | Inactive |   |

**Comment by tomalrussell** [comment]
As described (with several fields inactive), this is done.
