### ISSUE TITLE
db: Add source table

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#396]
Hi dom  Just to summarise plan is to have single dropdown for all categories with nesting. This will mean that the source list will be ever expanding - (and can be made open) of open or permitted  sources for information on London's building stock. The list will help people get a feel of where main repositories of information lie.  It also allows us to emphasise messages in relation to the platform e.g that all knowledge is encouraged and welcomed, that sources are essential, that historical data are vital for sustainability research owing to the stock being a very slow moving system, that we are also providing data on regulation, that we are also tracking performance, that we are promoting advanced computational approaches to building attribute generation as well.  This also allows users to assess uncertainty in more detail. 

Main sources can be extracted for each current ' info page' on the site- let's discuss.

Attach screenshots of table I'm working We could  simply start by asking - is the source based on a) first hand viewing  b) an  image  c) Another type of source 

![source 1](https://user-images.githubusercontent.com/42236514/63254157-233cff00-c26b-11e9-9fb7-bf69f51078c6.JPG)
![sources 2](https://user-images.githubusercontent.com/42236514/63254167-2637ef80-c26b-11e9-8d3e-d2e3ec993e5b.JPG)

This won't be perfect for launch just needs to be a good draft with main categories allowing for data to start be entered - with further work on it and the moderation a priority after October launch. Will talk to HE re moderation as part of the London Building Age Map project.

**Comment by dominijk** [comment]
Links to #356 #234

**Comment by dominijk** [comment]
@polly64 is this still relevant. It would be great to have the above in an editable format if so
