### ISSUE TITLE
UI/UX: Test alternate category names

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#397]
Hi dom On the the view map/edit page Can we try Age and History- instead of just Age.  Planning and Protection instead of just Planning.  Street and Environment instead of Greenery thanks

**Comment by dominijk** [comment]
Re-style  Links to #414 and #395 

@polly64 A quick sketch (not on live site) of what this would look like, also testing putting a bit more emphasis on the currently selected category;

<img width="718" alt="Screen Shot 2019-09-06 at 14 10 32" src="https://user-images.githubusercontent.com/6041913/64430398-21b76780-d0b0-11e9-8805-06541c521783.png">

**Comment by mz8i** [comment]
I think we need to coordinate any work regarding the layout on the data view/edit sidebar - both me and @tomalrussell have been working on changes to that so we need to be careful we don't do any work that would be later discarded.

**Comment by dominijk** [comment]
@mz8i Agreed these are edits using developer tool in browser only for quick sketching

**Comment by mz8i** [comment]
Sure. My point was that actually after @tomalrussell 's latest edits, this whole sidebar looks differently (see version from my dev env - with some additional small edits on top of Tom's):
![image](https://user-images.githubusercontent.com/36160844/64443187-508e0780-d0c9-11e9-97d2-774316ba4579.png)

Not sure if everyone knows about the latest state of this?

**Comment by tomalrussell** [comment]
Suggest closing this in favour of the status quo! @polly64 what do you reckon?
