### ISSUE TITLE
Add Location button for OSM WGS84 building centroid coordinate upload

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#40]
Can we add an additional button at the end of the' Location' for WGS84 centroid coordinate uploads  as suggested by an OSM contributor at the Alan Baxter consultation?  Perhaps we could call the box OSM WGS84 centroid to differentiate from OS data and to promote OSM's work? This would also signpost a very important but focused area that the OSM community specifically could perhaps help us with.

**Comment by tomalrussell** [comment]
Added coordinates and OSM id field - 4605cb6
