### ISSUE TITLE
Base selection outline colour on the current data colour scale

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#400]
For some of the data types, the colour scale for the buildings is very similar to the selection colour. For example, the colour scale for percentage of data filled contains only shades of blue, and it's sometimes very hard to see which building is actually selected.

To improve the user's experience, the colour of the selection outline should be determined for each colour scale separately, to choose the most contrasting colour. For example, for the blue scale of percentages, a red outline would be good.

Current:
![image](https://user-images.githubusercontent.com/36160844/63586661-c78bb200-c599-11e9-9b44-43784b8a65a5.png)

Suggested:
![image](https://user-images.githubusercontent.com/36160844/63587594-54376f80-c59c-11e9-9473-4425664e9e97.png)

**Comment by mz8i** [comment]
@polly64 what's your view on such a tweak?

**Comment by polly64** [comment]
Yes great looks good.  We will need to make slight adjustments to some colours over the next few months so will look at every again. but the red on this is very clear. Do send me or Dom or any other issues where u think clarity is an issue.

**Comment by mz8i** [comment]
Tackled by #423

**Comment by mz8i** [comment]
Closed by #423
