### ISSUE TITLE
Create/Test Discussion Thread Link from wix Category 'Location' data page

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#41]
On the wix site on the 'Data categories' page you can now click on whichever box/data category you want info for and go to a separate page for each - I should have pages for each category by 16 August. This also provides the 'info link' you need direct from the map.  

Each page will have the same format and give 1) Why we're collecting this data category 2) Ideas for sources of data, 3) Indication of Difficulty, 4) Indication of Level of Updating required  (ie High (for use), Low (for locational data, protection, designer/architect, building type), or Not needed (for Like me)).

You can see the format  if you click the 'Location' category.  This also includes a link to the 'Discussion thread' you suggested,  and lets you go straight to the map so you can start adding the data. It will be good to have threads for each category, as we release each, as well as a general one and a technical one.  This  category specific threads will allow us to pick up information to improve the content for each relevant page, as well as stimulating general discussion.

Could you possibly create a test thread I can link to the 'Location' page so I can get a feel? Also just email any comments/corrections/additions re text content on this page.

**Comment by tomalrussell** [comment]
Data category threads created at https://discuss.colouring.london/c/data-categories
