### ISSUE TITLE
Add HTML and semantic web metadata

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#412]
The website is missing metadata that is used by social media and other sites and devices to extract information about the site. For example, when sharing a link on facebook, the Historic England logo is picked up as the image for the website:
![image](https://user-images.githubusercontent.com/36160844/64166403-f0843080-ce3e-11e9-801b-9142de613a98.png)

- [x] [Facebook Open Graph](https://developers.facebook.com/docs/sharing/webmasters)
relevant links: [Facebook developer tools](https://developers.facebook.com/tools/debug/og/object/) to check the currently scraped metadata
- [x] [Twitter card metadata](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html)
- [x] Web app metadata for phones: [Manifest](https://github.com/h5bp/html5-boilerplate/blob/v7.2.0/dist/doc/html.md#web-app-manifest) and [Icons](https://github.com/h5bp/html5-boilerplate/blob/v7.2.0/dist/doc/extend.md#web-apps)

**Comment by mz8i** [comment]
@tomalrussell I will need a full good quality CL logo to generate all the necessary files for the web app icons etc. The one from Discuss is a bit low on resolution

**Comment by tomalrussell** [comment]
These should help - if you need to resize, avoid interpolation to keep the edges crisp.

32 
![logo-32x32](https://user-images.githubusercontent.com/2762769/64944234-d0ecff00-d865-11e9-9ca5-c713378cdf8c.png)
512 
![logo-512x512](https://user-images.githubusercontent.com/2762769/64944235-d0ecff00-d865-11e9-9ffd-e686235d40c4.png)
1280 
![logo-1280](https://user-images.githubusercontent.com/2762769/64944236-d0ecff00-d865-11e9-953a-8c8e0d596344.png)

**Comment by mz8i** [comment]
Closed by #426
