### ISSUE TITLE
UI/UX: Update side panel category names and order 

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#414]

**Comment by dominijk** [comment]
@mz8i  Can I transfer this one to you?

**Comment by mz8i** [comment]
Sure. Will coordinate with @tomalrussell

**Comment by mz8i** [comment]
@polly64 should I also update the WIX url to be `pages.colouring.london/streetscape` instead of `greenery`?

**Comment by mz8i** [comment]
Also, what should be the description? Currently, it's "Is there greenery nearby? Coming soon..."

**Comment by mz8i** [comment]
And the current subtitle is "Green context"

**Comment by polly64** [comment]
yes thanks, all 'Greenery' pages/sections/links should now read ' Streetscape'  and incorporate all previous Greenery content.   Dom and I will probably slightly adjust these secondary description  soon but for the moment if you could put 'What's the building's context?' that would be great.  The Main title should be 'Streetscape' the subtitle - (as I've now put on the Building Category 12 box graphic) is 
' Environment?'

**Comment by mz8i** [comment]
Closed by #428
