### ISSUE TITLE
UI/UX: Side panel hover highlight over category buttons

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#427]
Hi - following chat yesterday  I can't remember if on the sample the categories  highlight as you hover over them ? if they do already  just delete this issue. If not I think they might want to do this to encourage people to click on them

**Comment by dominijk** [comment]
@mz8i I think it does already?

**Comment by polly64** [comment]
ok great i just couldn't remember

**Comment by mz8i** [comment]
There is an outline in the standard selection colour that appears on hover. I think we could think about another way of styling that, for example with an animation, shadow, slight colouring highlight? But it's more cosmetic.

**Comment by dominijk** [comment]
Thanks for confirming
