### ISSUE TITLE
UI/UX: Main site tool bar Hello link

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#430]
Via email linkes to #394 

The current live site has duplicate links `Hello` and `More about` before point to same static site page as below. @mz8i is one that has already been addressed part of your recent updates? 

<img width="1763" alt="Screen Shot 2019-09-26 at 14 40 27" src="https://user-images.githubusercontent.com/6041913/65693274-f0f19f00-e06b-11e9-8a54-d8987789c17f.png">

**Comment by mz8i** [comment]
This is no longer relevant after the recent changes
