### ISSUE TITLE
UI/UX: Type category  - Activate attachment maps

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#436]
**Dependencies** 
Run type (014) migrations 

**What UI does**
Allows input for two fields;
- Building attachment type (inputs to db field `building_attachment_form`)
  - Detached
  - Semi-Detached
  - End-Terrace
  - Mid-Terrace
  - Unknown 
-  Date building use changed (numeric constraint can't be greater than current year or less than 0) 

**What map looks like**
For launch, on category load this will be the `building_attachment_form` field. Initial colours as below;
  - Detached `#f2a2b9`
  - Semi-Detached `#ab8fb0`
  - End-Terrace  `#3891d1`
  - Mid-Terrace `#226291`
  - Unknown `#aaaaaa` 

Post launch enable height map, landuse map dependent on #358

**Comment by dominijk** [comment]
Copy for type;


category | field label | tool tip | db_field | active
-- | -- | -- | -- | --
type | Building configuration   (attachment)? | We have prepopulated these based on their   current attachment. A building can either be detached, semi-detached or part   of a terrace (middle or end) | building_attachment_form | yes
type | When did use change? | This is the date the building stopped being used for for the function it   was built for. I.e. I.e. If it was Victorian warehouse which is now an office   this would be when it became an office or if it was something before that,   maybe a garage then the date that happened | date_change_building_use | yes
type | Original building use | What was the building originally used for when it was built? I.e. If it   was Victorian warehouse which is now an office this would be warehouse | not yet added to db | no

**Comment by mz8i** [comment]
@dominijk the table contains fields from sustainability category, is this intentional?

**Comment by dominijk** [comment]
No, edited they're all taken from same sheet
