### ISSUE TITLE
Sign up - Contributor agreement

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#44]
When we're working out what people have to tick when signing up re data protection think we also need to have something you tick where we say  'We are unable to accept any data derived from restricted sources' or something like that.  maybe there is a standard form we can use. See also Monday2 0th Aug  email and Issue #48  for dropdown list

**Comment by tomalrussell** [comment]
Look into contributor agreements or guidelines for other crowdsourcing projects (OpenStreetMap/Wikipedia?) and make clear that data collected will be made available under the ODbL

**Comment by tomalrussell** [comment]
(Note issue #48 lists user categories for leaderboards; part of the sign-up process but not dependent on this issue)

**Comment by tomalrussell** [comment]
# Draft contributor agreement - edit inline/comment below

## Open data

Colouring London contributions are *open data*, licensed under the [Open Data Commons Open Database License](http://opendatacommons.org/licenses/odbl/) (ODbL) by Colouring London contributors.

You are free to copy, distribute, transmit and adapt our data, as long as you credit Colouring London and our contributors. If you alter or build upon our data, you may distribute the result only under the same licence.

## Your contributions

Colouring London emphasises local and community knowledge. Contributors use a variety of sources and local and expert knowledge of buildings to contribute data and verify that Colouring London is accurate and up to date.

When you contribute to Colouring London, you make your contributions available as open data for anyone to copy, distribute, transmit and adapt in line with the licence.

We are unable to accept any data derived from copyright or restricted sources, other than as covered by fair use. 

We encourage full attribution of data sources where appropriate - more details on potential sources are documented with suggestions for each [data category](https://www.pages.colouring.london/buildingcategories)

When you make a contribution to Colouring London, you are creating a permanent, public record of all data added, removed, or changed by you. The database records the username and ID of the user making the edit, along with the time and date of the change. All of this information is also made publicly available through the website and through bulk downloads of the edit history.

**Comment by polly64** [comment]
Hi Tom this looks great.

**Comment by martin-dj** [comment]
It looks good. One point though. Is it necessary to include the username in bulk downloads? This could constitute sharing personal data with a 3rd party.

**Comment by tomalrussell** [comment]
Yes - username is part of the public record of contributions. This is in line with how wikipedia and openstreetmap handle it.

**Comment by tomalrussell** [comment]
Closing as draft looks ok. May revisit if any further feedback/guidance comes along.
