### ISSUE TITLE
Simplify withCopyEdit in data-container

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#453]
From comment on https://github.com/tomalrussell/colouring-london/pull/448#pullrequestreview-296308282 - come back to `data-container.tsx` to reduce repetition and simplify conditional rendering.

**Comment by mz8i** [comment]
This was already slightly re-worked in https://github.com/tomalrussell/colouring-london/pull/472/commits/3a35f5dab58fe34411fb3d34d701d18440554cc8 - I think we might be OK for now. The `WrappedComponent` is still referenced twice in the JSX, but I didn't see an easy way to simplify it further
