### ISSUE TITLE
TS interfaces for proptypes of Category and Categories

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#456]
see comment: https://github.com/tomalrussell/colouring-london/pull/403#discussion_r318006280

as part of ongoing work to statically type the codebase

**Comment by mz8i** [comment]
As part of this, I'd suggest implementing a mechanism for generating the React propTypes from the TS interfaces and removing the manual propTypes definitions - see https://github.com/milesj/babel-plugin-typescript-to-proptypes
