### ISSUE TITLE
Twitter card

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#459]
Just noticed that the twitter card for http://colouring.london & http://colouringlondon.org is showing a cropped version of the logo - see attached screenshot (tweet showing the card also linked here https://twitter.com/LDN_CDO/status/1179698266990096384)
 
Wanted to let you know as now the Colouring London website is being tweeted out quite a bit – would either of you be able to fix it? @mz8i can you have a look at this

**Comment by mz8i** [comment]
Will do now. We need a square image probably for that purpose, will create one

**Comment by mz8i** [comment]
Image updated, and Twitter card cache purged using https://cards-dev.twitter.com/validator
The new square logo image shows up in the above tweet already: https://twitter.com/LDN_CDO/status/1179698266990096384
