### ISSUE TITLE
Data layer being reloaded when initial few buildings selected

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#461]
Upon a fresh load of the data map, when the user selects a building, a complete reload of the map layers is triggered, resulting in annoying blinking.

Whether there is a blink or not seems to be related to which building is selected, and the sequence in which they are selected. The same buildings seem to consistently trigger a reload, for example Euston station main polygon seems to trigger a reload no matter how many previous buildings were selected.

Without looking at the code, the first guess is something to do with revision ID being updated on select? Any guesses @tomalrussell ?

![colouring_blink](https://user-images.githubusercontent.com/36160844/66311097-9414a500-e905-11e9-9886-43a38b96e241.gif)

**Comment by tomalrussell** [comment]
The tilelayer reloads when the app sees a higher revision id than previously encountered.

See [src/frontend/map-app.tsx#L89](https://github.com/tomalrussell/colouring-london/blob/master/app/src/frontend/map-app.tsx#L89)

This only really needs to happen when a user edits a building.

Suggested way to avoid it happening when just viewing: set the revision id to the maximum (latest revision id from edit logs). Load the max revision id as part of general app startup or navigation to the map page.

**Comment by mz8i** [comment]
Makes sense! I will work on this some time soon as it's quite annoying for the user and occurs so regularly

**Comment by mz8i** [comment]
Resolved by #485
