### ISSUE TITLE
Top menu bar, branding, and moving colouring London logo

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#468]
Hi - following chat re neatness of dropdown menu also, think we need to swap the moving logo for our standard logo on the view/edit page so we're properly branded here  and we clearly link  link colours/categories/ logo. The moving logo is v good on all other pages though wondered if you could change the animation so instead of being random movement of logo colours across the grid it is more structured so that a colour always appears in its correct boxes - then just turn on and off at different times, or according to set patterns. We really want the logo to start being recognised and get the branding going so if we can test this as soon as possible that would be great.

**Comment by mz8i** [comment]
We can easily switch to a static, canonical logo for now - and re-think what animation style and where we want it? What do you think @polly64 @tomalrussell

**Comment by polly64** [comment]
Think that would be great just for the View/Edit pages at the moment and and all Map keys (currently just grey grids) if we can, as people will be taking screen shots of maps so we want CL to always be referenced.  For all other pages we can chat in a couple of weeks. many thanks

**Comment by mz8i** [comment]
My only comment on the logo in the legend would be that from a usability/visual cognition point of view, mixing the branding colours with the data colours inside the legend might decrease the overall legibility - which I think was the initial reason to make the logo grid grey in the legend.
I understand we need to balance different priorities, and the branding is an important one, but we might want to think about smart ways of presenting both next to each other so as not to confuse the users and not take too much space?

**Comment by polly64** [comment]
Yes totally understand. let's leave key for moment til we have time to discuss in detail
