### ISSUE TITLE
Maciej- location and land use colours

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#469]
Hi Maciej i've looked at the category colours as shown on map page on a few machines and 'land use' and 'location' colours are the ones that are proving a bit problematic. Though fine on mine the 'location' orange looked a bit murky and the 'land use' yellow comes across as a bit green on the other screens.  We want to get them as clear and clean as possible  so if u could have a quick look and see if you can just make a slight adjustment on each to counter this that would be great, many thanks.

**Comment by mz8i** [comment]
I can actually see that some of the colours (including location and land use) differ slightly from those on WIX page. I will take those as authoritative and adjust. Sorry for missing that earlier!

**Comment by polly64** [comment]
no problem at all thanks v much


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________
