### ISSUE TITLE
release dates for listed building, 'community' and land use uploads

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#475]
Hi  could u chat re etas for Listed buildings, and for the 'community' and 'land use' categories? Know they're nearly ready to go.  Can we release all within next 3 weeks? Needed by end of November latest. Many thanks

**Comment by dominijk** [comment]
Listed buildings - data is in refer to #538 for this
Landuse - This is done
Community - Links to #432 #327. In terms of bulk data we could automatically set some buildings as community where land use has been provided
