### ISSUE TITLE
Latitude and longitude input errors

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#488]
The edit form rejects longitude/latitude values which are already in the database. For example, when trying to edit 22 Gordon Street (Bartlett School of Architecture building - ID `2481675`) data, upon editing any field, the form cannot be submitted because the browser validation complains about the lat/lon fields.
The latitude value is `51.52587` and the browser shows the message `Please select a valid value. The two nearest valid values are 51.5258 and 51.5259` - similar for longitude

**Comment by tomalrussell** [comment]
Frontend fix is to change `step` to a smaller number, e.g. in this case 0.00001.

Overall we should be consistent in what's accepted in the frontend, through the API and in the database with that precision. 

Frontend validation:
https://github.com/tomalrussell/colouring-london/blob/fb0358e5b1afdfbf92d43ff91964ef5e142a1b70/app/src/frontend/building/data-containers/location.tsx#L98

Backend validation:
- anything more than whitelisting fieldname and passing to db wrapper? TODO?

Database field:
https://github.com/tomalrussell/colouring-london/blob/fb0358e5b1afdfbf92d43ff91964ef5e142a1b70/migrations/004.location-date-size-like.up.sql#L23
