### ISSUE TITLE
Simple screen to see all recent edits

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#499]
Create a simple screen showing all changes to the database from the last 3 weeks (time span to be adjusted?). This is to be displayed in a similar fashion as the current building edit history screen, but with edits for all buildings displayed in one place, and each position in the list linking to the edit page of the edited building.
This is a temporary solution to facilitate a retrospective review of recent data edits.

**Comment by tomalrussell** [comment]
Sounds good - I suggest this is viewed as a permanent addition, as a useful view of the whole edit history.

Regarding time span, perhaps we shouldn't limit it by date but instead add pagination and show 50 or 100 edits per page, with the ability to go back through all edits.

**Comment by mz8i** [comment]
I agree that this should be a permanent addition, however the current direction is to have something up and running as soon as possible, hence the simplifications (no pagination etc). Let's improve this further in a next issue.

**Comment by mz8i** [comment]
Closed by #503.
The screen currently displays last week of changes.
