### ISSUE TITLE
Update source attribute for Age category

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#500]
Because of recent increase in data edits, the Age source needs to be improved as soon as possible by adding some options for source - before the more general mechanisms described in #356, #396, #492 etc are implemented.

This entails (list after recent meeting):
- [ ]  adding source options: "Other database", "Film/video", "Local knowledge"
- [ ] renaming some source types (this might be problematic in relation to edit history, ideally we wouldn't modify existing enum values)
    - "Archive research" -> "Archive documents"
    - "Other website" -> "Website"
- [ ] reordering source types in the drop-down list:
```
Survey of London
Pevsner Guides
Local history publication
Other book
National Heritage List for England
Other database
Historical map
Archive documents
Film / video
Expert knowledge of building
Local knowledge
Website
Other
```
- [ ] display a prompt to add source details when one of the "other" options is selected (related to #103)
- [ ] I also found issue #156 which talks of the type "Building front/facade" - is this still something we want to add? Is it replaced by the newly proposed "Local knowledge"? If we want to add it anyway, where should it sit on the list?

@tomalrussell could you please give your opinion on these steps, especially the renaming of existing enum fields

**Comment by tomalrussell** [comment]
- adding options :+1:
- reordering :+1:
- add prompt :+1: - I imagine this would be a styling change to highlight the source details field
- building front :+1: to include, if @polly64 still thinks it would be useful

On changing values, fine in principle but possibly a bit more work:
1. Do any buildings currently have "source" set to either of the values which we would change? If not, we can change the enum directly
2. If any do use those values, I suggest we migrate as follows:
  - add new values to the enum (e.g. "Website")
  - make edits to all buildings with the old values, change to the new values (e.g. "Other website" > "Website" for building 123)
  - remove the old values from the enum (e.g. "Other website")

I think we should view the edit history as decoupled from the way the data is stored, so if some old values reflect enum values that no longer exist, that's okay. But if we do want to change a value, that should be reflected by new entries in the edit history - i.e. it's immutable and append-only.

**Comment by polly64** [comment]
Hi, building front/facade doesn't need to be included in source list- (it only occurs in list of attributes being collected under age).
Also to say a user may also want to add multiple historical sources as they may for example have found on the facade date from a different place to the original date of construction for the main core.  There is no need to separate these out however to link to the individual attribute subcats. They can all be bunched under Source/sources as now but might be easier perhaps to have a + sign and hint ' add another source'. Also I just added some info on the age section and I noticed I was putting the website link twice - once under source, and once under text and images.  Think would be easier (and reduce unnecessary duplication if we could  change  the ' images and text ' url box to 'Other relevant website links'

**Comment by mz8i** [comment]
@tomalrussell I only now realised on closer inspection that the `date_source` column in the database does not use an enum, it's just a character type... Which means that right now one can set any value to that field through the API - it's only the front-end that offers a choice of options. Do we want to move to using an enum here, like it's being done in some of the more recently added fields?

**Comment by mz8i** [comment]
By the way, here's a summary of the current values in the live db
```
            date_source             |  count  
------------------------------------+---------
 <no value>                         | 3524536
 Other website                      |     341
 Expert knowledge of building       |     116
 Survey of London                   |      76
 Other                              |      68
 National Heritage List for England |      53
 Historical map                     |      30
 Local history publication          |      27
 Pevsner Guides                     |      14
 Archive research                   |      12
 Other book                         |       9

```

**Comment by dominijk** [comment]
@polly64 As discussed the first table is categories people have already put data into the second is an additional two categories 

|date_source|update_to_if_not_blank|
|-----------|-----|
|Archive research| Archive research (documents & photos|
|Expert knowledge of building||
|Historical map||
|Local history publication||
|National Heritage List for England||
|Other||
|Other book||
|Other website||
|Pevsner Guides||
|Survey of London||

Extend table adding 

|date_source|update_to_if_not_blank|
|-----------|-----|
|Local knowledge or current image||
|First hand knowledge||

**Comment by polly64** [comment]
Hi Dom and Maciej sorry moving these around but think it's going to take a bit of testing. I have kept as close  as possible to original as per our discussions.

 i realise expert knowledge can be viewed as either local/occupant or professional so this can double as first hand knowledge Dom so we don't need this as well . 

let's just add 2 new ones:  'Expert estimated from image'' and 'Other database or gazetteer' - positioning the latter directly under the National Heritage List for England. Also add Victoria County history as a book as important one.  (We don't want estimates from images that aren't expert as we really want this only to be done by professionals and for non-professionals to help us find other sources)

So the list should read in this order:
1. Expert knowledge of building
2. Expert estimate from image
3. Book - Survey of London, Pevsner Guide, Victoria County History, Local History Publication
4. Other book
5. National Heritage List for England
6. Other database or gazetteer
7. Historical map
8. Other archive resource
9. Other website
10. Other

**Comment by polly64** [comment]
hdom

**Comment by polly64** [comment]
Hi Dom re list of sources in issue https://github.com/tomalrussell/colouring-london/issues/396 I forgot i'd done this and think it's better for moment just to add category by category.  Of the 12 categories we have already covered Location, Land Use, Type, Age, Team, Like me.

**Comment by mz8i** [comment]
Hi all, @polly64 changing spec is OK (although good that I haven't yet implemented this feature because otherwise we'd have to re-do it :) ) but we need to make sure that we're precise about the desired end result. For that, we need a precise "translation" map between what values there currently are in the database, and what values there will be after the change. See below for my attempt of formalising such a map:
```
Current Value                      |  Updated Value
---------------------------------------------------------------------------------------------
Expert knowledge of building       |  Expert knowledge of building
<DOES NOT EXIST>                   |  Expert estimate from image
Pevsner Guides                     |  Publication - Survey of London, Pevsner Guide, Victoria 
Survey of London                   |  Publication - Survey of London, Pevsner Guide, Victoria 
Local history publication          |  County History, Local History Publication
Other book                         |  Other publication
National Heritage List for England |  National Heritage List for England
<DOES NOT EXIST>                   |  Other database or gazetteer
Historical map                     |  Historical map
Archive research                   |  Other archive document
<DOES NOT EXIST>                   |  Film/Video
Other website                      |  Specialist website
Other                              |  Other (not sure we need this one)
```
On the left are values that are currently in the database. On the right, values that the former would be translated to.

Please not that for example according to my understanding of the latest specification, `Publication - Survey of London, Pevsner Guide, Victoria` is one value - so where previously there would be a record of exactly which publication was the source (e.g. Survey of London or Pevsner Guide), now it would be only known that it was one of the three (Survey, Pevsner, Victoria) but not which one exactly (just making sure that's the desired result). Like we agreed, we are not going to go for hierarchical fields for now, so the translation from old to new should be kept to the simplest possible.

Also, I noticed that one category dropped from the proposed new list is `Local knowledge`. I agree it was a bit ambiguous, but that means we essentially don't have a category for local non-professional knowledge of a building.

Also, would a Wikipedia article fall under `Specialist Website` or `Other`?

**Comment by polly64** [comment]
Hi Maciek- 
1. yes local knowledge goes because either u consider yourself expert enough to know building or you need to give us a detailed source
2. OK yes agree let's make Specialist website 'specialist/other website to be clearer
3. So in longer does that mean  say ' historical map' could be removed as a discrete category and easily subsumed as part of a dropdown within 'Archive documents?
4. I'm finding the publications one tricky so I'll just give you my  ideal longer term scenario and then let you choose however  you want to do it for the moment : Ideally we would have it saying 'Publications' and then the dropdown would say - in this order- Survey of London, Pevsner Guide, Victoria County History, Conservation Area appraisal, Local history publication, Other.
let me know if you need anything else

**Comment by dominijk** [comment]
The way I had thought of this workings with publications as an example would be;

Choose `Publications` from a drop down list. Selecting publications then reveals another input box with list of publications and also an input option to add specific volumes / pages etc. In view mode the source is surfaced under the field as suggested in #492

**Comment by mz8i** [comment]
Final translation table after comments. Please note this still stays in the framework of single dropdown for source type + free text source details. Conditional dropdowns will be considered later as part of another issue.

```
Current Value                      |  Updated Value
---------------------------------------------------------------------------------------------
Expert knowledge of building       |  Expert knowledge of building
<DOES NOT EXIST>                   |  Expert estimate from image
Pevsner Guides                     |  Pevsner Guides
Survey of London                   |  Survey of London
<DOES NOT EXIST>              | Victoria County History
Local history publication          |  Local history publication
Other book                         |  Other publication
National Heritage List for England |  National Heritage List for England
<DOES NOT EXIST>                   |  Other database or gazetteer
Historical map                     |  Historical map
Archive research                   |  Other archive document
<DOES NOT EXIST>                   |  Film/Video
Other website                      |  Specialist website
Other                              |  Other
```

**Comment by polly64** [comment]
great!

**Comment by mz8i** [comment]
I released the new list of choices and renamed `Archive research` -> `Other archive document` and `Other book` -> `Other publication`. For now, I actually held off with renaming `Other website` - I can see that really a lot of the sources there are Wikipedia. Do we really want to rename that to `Specialist website`?

**Comment by polly64** [comment]
agree if this is the case just call it ' website'
