### ISSUE TITLE
Consider removing propTypes generation

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#547]
The mechanism to auto-generate propTypes was implemented in #489, but it might actually make sense to remove that mechanism altogether. Some considerations:
- the mechanism relies on transforming the code with both the typescript toolchain and Babel (while using @babel/plugin-syntax-typescript) - this creates slight complications when using e.g. the TS 3.7 features like the `?.` or `??` operators which are not part of ES standard yet and are not supported by the Babel TS plugin
- during implementation of #489 it turned out that the Babel plugin for propTypes generation has some limitations, for example it cannot generate some more complex propTypes definitions, and there is a lack of a good mapping between propTypes `isRequired` and TS required vs non-required field (denoted with a question mark). For example, a property like `{ name: string }` in TS can still be assigned a nullish value e.g `<Foo name={null} />` as long as there is an explicit assignment. Meanwhile, the Babel plugin will generate a propType with the `isRequired` modifier for every TS field that doesn't have a question mark next to it's declaration. This will generate a propTypes error at runtime in case the prop value is null or undefined, which is a different behaviour. To remove the warning, a question mark can be added to the TS declaration, but then an error won't be generated by TypeScript if the property is completely omitted. This could increase the risk of programming errors.
- there's only a limited number of cases where both TS types and (even auto-generated) PropTypes make sense together (see discussions on [StackOverflow](https://stackoverflow.com/a/43187969/1478817) and [dev.to](https://dev.to/tschaka1904/react-proptypes-vs-typescript-any-experience--bm9)) - mostly when accepting external data like that from API calls etc

The question is, with the limited usefulness of TS+propTypes, is it worth the complexity it creates in terms of the build process and the need to either ignore errors during development or re-write much of the TS types to suit the stricter nature of PropTypes `isRequired`?

I am leaning towards removing the auto-generation altogether to make our lives easier, but would like to hear some comments, especially from @tomalrussell

**Comment by tomalrussell** [comment]
As discussed, I think it's fine to drop the auto-generation.

If we decide they're needed later we can look at other methods (the `inferPropTypes` thing or writing and maintaining the boilerplate).

It's a plus if our babel pipeline gets any faster and/or simpler.
