### ISSUE TITLE
Night time /Daytime view

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#55]
We might need to label backgrounds Daytime/Edit view   and Night time view as people can't read the street names on latter? can we do anything about this?

**Comment by tomalrussell** [comment]
We could default to the 'Daytime' basemap when a user starts editing.

Labelling might help, too - we need to teach people that they can switch to whichever basemap they prefer for the task at hand.

**Comment by polly64** [comment]
Yes let's do that re default.  and also add the words re Night time daytime instead of layer sign

**Comment by tomalrussell** [comment]
Done with theme-switcher, as of a6d1b309a44abf388ee7fd3530bfa99f862336d4
