### ISSUE TITLE
Reset password flow

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#61]
- [ ] View reset password request form (email address)
- [ ] Generate token
- [ ] Send email (look at mailgun)
- [ ] Validate token
- [ ] View reset password form (new password/confirm)
- [ ] Update password + login

**Comment by mz8i** [comment]
@tomalrussell If the user registered without an e-mail, then it's not possible to reset a password, right?

**Comment by mz8i** [comment]
Re mailgun, do we actually want to use that platform?

**Comment by tomalrussell** [comment]
Can you flesh out pros/cons/options?

- Simply sending from the server
- we do have a mailgun account already; the discourse forum uses it for transactional emails
- data protection considerations?
________________________________

**Comment by mz8i** [comment]
If we already have an account then I think it makes sense to use it! I'll read up on how to set up Node as a client

**Comment by mz8i** [comment]
I think we should use Mailgun but over SMTP rather than using their proprietary API, and use some popular library like Nodemailer on the Node side - this way we only need to change the endpoint information if we ever want to switch for example to a self-hosted SMTP server.

**Comment by dominijk** [comment]
Lfgss.com use a service (mircosm?) which works well based on my experience of using it for a few years. I don’t have a password just an email,  when I clear my cache or login elsewhere i just enter my email and get a new PIN number emailed which the client holds onto

**Comment by tomalrussell** [comment]
@mz81 - :+1: making it easy to switch provider, mailgun+smtp+nodemailer sounds like a good approach

@dominijk :+1: email-only login - should be covered by #62
