### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#63]
- [ ] Delete account form, linked from my-account
- [ ] Double-check that they want to delete!
- [ ] User delete API endpoint (must be authenticated)
- [ ] Remove user details (email/password/registered) from database
- [ ] ~~Create unique username? `deleted_user_123`~~

Make clear that this will not remove references from the edit log - be clear that it's not possible to retract contributions, that old archives with username will continue to be publicly available.

**Comment by mz8i** [comment]
By removing user details, do we mean deleting the row from the database, or clearing the selected columns containing personal info? If the latter, would we want an additional deleted flag column, or do we want to check whether a certain column is null

**Comment by tomalrussell** [comment]
I think we should leave the record in the database and clear selected columns containing personal info (username, email, password).

This way the edit history (which has a foreign key reference to user) can be left unchanged.

`username` is constrained to be unique and not null - is there a common way of handling this for deleted users? We could replace the old username with `deleted_<UUID>` or similar randomly generated placeholder

Yes, adding a deleted flag column sounds sensible.

**Comment by mz8i** [comment]
I think that's a good approach, but I am wondering about what to rename the user to:
- does anyone else care if the user is deleted? Should we just rename to 'user-<UUID>'?
- an UUID is 128 bits, that's 32 characters plus the standard format is hyphenated, e.g. `user-a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11` is 41 characters and the username currently has a constraint on 30 characters.

Anyway we'll create a `deleted` column then, default to false.

**Comment by mz8i** [comment]
Alternative would be to change the unique constraint to a partial unique index: https://stackoverflow.com/a/16236566 so that the uniqueness requirement does not apply to deleted users, and just rename all users to `deleted-user` - from a design point of view, it would only be the question whether we want people to see that certain edits were made by distinct deleted users - in which case the first solution is better, but would require increasing the upper limit of characters or using a shorter UUID

**Comment by tomalrussell** [comment]
Using a shorter UUID should be fine - the intention is to quickly randomly generate a placeholder username, avoiding conflicts with any existing usernames, using UUID as such isn't key.

I don't think there's any reason to hide that edits were made by distinct deleted users - we'll have already made public the old edit history with the original usernames as open data.
