### ISSUE TITLE
Configure rate limiting

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#66]
See https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-http/

**Comment by martin-dj** [comment]
Completed by additions to  NGINX config file as follows:

```
# Configure rate limiting
limit_req_zone $binary_remote_addr zone=one:10m rate=100r/s;

server {
    ...
    location / {
        # apply rate limiting
        limit_req zone=one burst=100 nodelay;
        ...
        proxy_pass http://appserver/;
    }
...
}

```

The `rate `and `burst` values were determined by trial and error and appear not to affect the loading of pages but may need reviewing in the future. The values may seem high but a single incoming HTTP request creates multiple further requests for resources.
