### ISSUE TITLE
Make clearer if on Edit or View Page

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#69]
Could we try something like 'VIEW MAPS'  in caps possibly  at top of view only map page, and close by or as a hover  add ' Edit maps here' to get you to from there to edit map page

On editing page '  EDIT MAPS'   at top  with something like ' return to viewing maps here' closeby or as a hover

Also can we add View maps and Edit maps on the top bar so people can see them

Just really need it to be super easy for people to see if they are Editing or Viewing

**Comment by tomalrussell** [comment]
Sidebar title is now 'View Building/Edit Building' as of 18d95491be7f168e3916d34ef30d2c9ff4abac21

There is no 'edit maps' page - only 'edit building' - we can only edit one building at a time, it doesn't make sense to be editing the maps without editing a building:
1. View colour maps
1. Select a building (to view)
1. Start editing that building, or go to (1) or go to (2)

**Comment by tomalrussell** [comment]
Closing - we can review design if needs be.
