### ISSUE TITLE
Can we highlight building with hover first as SofLondon

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#70]
https://surveyoflondon.org/map/
can we use Duncan's technique of hovering as here?

**Comment by tomalrussell** [comment]
No - Survey of London use their own geometries, so have access to them in the front end. We rely on the server to render the highlighted image because we can't release the OSMM geometries, nor the spatial link to UPRNs.

**Comment by polly64** [comment]
ok re my last email just now  i will show this to jeremy and just chat to him  thanks


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________
