### ISSUE TITLE
Change 'core' storey wording

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#71]
tried this out on teenage users yesterday and they got confused. 
can we change to
'Total number of storeys'  and to omit Core - Also  Hover on this to read  ' Ignore half landings and cellars'

Can you put to the top, not second down- again makes it easier- thanks

**Comment by tomalrussell** [comment]
Following further comment, left this as "Core storeys" (hint: "How many storeys between the pavement and start of roof?") but moved it to the top.
