### ISSUE TITLE
some polygons not highlighting

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#74]
you probably have seen this already but attach a screen shot of some missing OSMM polygons in a terrace
![osmm snip](https://user-images.githubusercontent.com/42236514/46276986-a83aff00-c559-11e8-875a-5f0c4ff8cdbf.JPG)

**Comment by tomalrussell** [comment]
See also #49 ?

**Comment by tomalrussell** [comment]
Closed with data update
