### ISSUE TITLE
Last not first address entered showing below so easy to select

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#75]
Hi have just  added stuff on theberton road. So exciting!   a) does it matter whether i add in caps for lower case as for the postcode it doesn't automatically adjust?  b) can the last address u type in come up.   My default seems to be **first** address i ever typed can it be the **last**? just makes it much quicker if you're doing a street

**Comment by tomalrussell** [comment]
The default repeat/autofill behaviour is defined by the browser, not something we control - copy/paste is probably best here.
