### ISSUE TITLE
'click a building to edit' sign

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#76]
is this possible ?- as in Survey of London whitechapel.  If complicated can we (temporarily?) have a notice on main maps screen  say ' click a building to edit' as not obvious you need to click it.

**Comment by tomalrussell** [comment]
Not possible with our restrictions - see #70 

Adding help and instructions definitely the way forward.

**Comment by polly64** [comment]
just about to see jeremy morley from os as he happens to be in- are there any specific restrictions we want to ask them to lift to help this?


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________

**Comment by tomalrussell** [comment]
Added 'click map' hint as of b438e885c047d2bd9031e5f227421658f4db2b6e

Noting for reference - Survey of London Whitechapel download the full set of building geometries to the client as GeoJSON, then render as SVG for snappy interaction. This works well for small datasets, we'd need a different technical solution (e.g. [vector tiles](https://www.mapbox.com/vector-tiles/)).

For licensing - I think we'd need to be able to share the full building geometries with any site visitors.
