### ISSUE TITLE
Activate address fields in Location category

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#849]

**Comment by edwardchalstrey1** [comment]
@polly64 it looks like the "Building number" field in the "Location" category is already limited to alphanumeric. 

I think what you mean here is to activate these other fields so they can be edited?
<img width="464" alt="Screenshot 2022-07-05 at 15 55 18" src="https://user-images.githubusercontent.com/5486164/177357332-b3516cbc-1bd1-4b97-bcb1-e3ddb53c7cf7.png">

**Comment by edwardchalstrey1** [comment]
@polly64 you can ignore the above, I have implemented this now :)

**Comment by polly64** [comment]
yes and say make post code only alphanumeric and max 8 digits, and building name/address (both lines) maximum number characters

Polly Hudson
Senior Research Fellow, The Alan Turing Institute
Project Lead:  Colouring Cities Research Programme
https://www.turing.ac.uk/research/research-projects/colouring-london-and-colouring-cities-research-programme

The Alan Turing Institute is the UK's national institute for data science and artificial Intelligence.
The Alan Turing Institute is a limited liability company, registered in England with registered number 09512457 with registered offices at British Library, 96 Euston Road, London, England, NW1 2DB. We are also a charity registered in England with charity number 1162533. DISCLAIMER: Although we have taken reasonable precautions to ensure the completeness and accuracy of this e-mail, transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or be incomplete. If you receive a suspicious or unexpected email from us, or purporting to have been sent on our behalf, particularly containing different bank details, please do not reply to the email, click on any links, open any attachments, or comply with any instructions contained within it. Our Transparency Notice found here - https://www.turing.ac.uk/transparency-notice<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.turing.ac.uk%2Ftransparency-notice&data=04%7C01%7Cphudson%40turing.ac.uk%7C2324b5e120b4425faf7908d97c41c292%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637677444135244977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O4PMzDkukkzcBZkAX0ILaaWfe1T%2F7dsBTZsm%2FYKmolA%3D&reserved=0> sets out how and why we collect, store, use and share your personal data and it explains your rights and how to raise concerns with us.
________________________________

**Comment by edwardchalstrey1** [comment]
@polly64 yep, postcode is max 8 characters - how many characters do you want to limit the building name/ address to? I feel like this is going to be difficult to constrain sensibly, unless we just do a really big value e.g. 1,000 just to prevent it being infinite - what do you think?

**Comment by polly64** [comment]
@edwardchalstrey1 thanks great re post code . Let's restrict address to one line of 30 characters which must have a space (i.e. gap for street/road to be added) we have post code so findable with road and number. Also- urgently- could you make the 'building name' to say ; add link for building name if any' and then make it only possible to add a link here not free text. This is where OSM had a lot of expletives for white house so key vulnerable subcategory

**Comment by edwardchalstrey1** [comment]
@polly64 looks like there are separate fields for Street and 2nd line of address, so I have limited them each to 30 characters - not sure we should enforce a space in either as I could imagine edge cases where they are each one word - what do you think?
![Screenshot 2022-07-06 at 15 26 02](https://user-images.githubusercontent.com/5486164/177574324-a0e9ec1b-0d1e-4784-abfa-fa742fbe8473.png)
 
I'm confused by the "Building name" it seems like this should be a name, not a link - do we need to add a new field called "Source link for building name" similar to what we've done elsewhere?

**Comment by polly64** [comment]
i just want to put this in temporarily to test it. Because we know it is vulnerable to malicious text. So u can link to houses of parliament site say for now. Most buildings in London won't have a name.

**Comment by polly64** [comment]
no dont need source just have link straight in box

**Comment by edwardchalstrey1** [comment]
@polly64 I've done this now and renamed the field and tooltip to make it clearer what we're asking for - let me know if you want to change anything:
![Screenshot 2022-07-07 at 10 37 19](https://user-images.githubusercontent.com/5486164/177743017-fe059e49-d58a-47aa-be6d-614344154182.png)
