### ISSUE TITLE
Cache low-zoom map tiles

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#85]
Server-side cache, periodic rerender

**Comment by tomalrussell** [comment]
Related project: https://github.com/mapserver/mapcache 
- supports multiple cache mechanisms (memcache/filesystem/sqlite...)
- supports seeding cache, configuring fast/slow layers
- runs as an Apache module (nginx support labelled experimental) 

Not possible to use with current setup, cautious of introducing dependencies, may be worth revisiting later.

**Comment by tomalrussell** [comment]
Basic filesytem caching in place. Need to look at:
- [ ] warm cache programmatically - currently only cold-start, low-zoom requests require a lot of work
- [ ] expire/re-seed (a) on schedule (daily?) (b) on edit (evict upwards, re-render down?)
- [ ] decide on best zoom level thresholds cache/not, stitch/render
- [ ] discuss map style and clarity - likely knock-on issues with colour, labels

**Comment by dominijk** [comment]
Looks good! On styling, at the highest zooms the labels obscure some of the data to my eye so maybe we can edit the style to make them smaller. The alternate could be  a label that appears on hovver over following the mouse or something programatic that labels according to clusters of data on the map if we can get that to work.

**Comment by polly64** [comment]
yes fantastic Tom. 
Dom can you possibly send me a list of the missing conservation boroughs? I'll send a round robin to the LAs to say we're missing their data and also can they supply their local lists - which I'll collate.
Re styling 
a) we've also got an issue of labels appearing under the data at certain scales   
b) Can we lock the screen at full zoom out at the Greater London boundary- but not super tight to it
c) Can we try a lightish grey line for the Greater London boundary outline- So quite thin and elegant on maximum zoom out but also legible on the night and day backgrounds
